openclarity/vmclarity

backend/pkg/database/odatasql/query.go, backend/pkg/database/odatasql/query_test.go
This fixes startswith and endswith filters by ensuring that we're getting the SQL representation of the string field and not the JSON representation of the string with builtin quotes. To prevent regressions this commit also adds missing unit tests for these filters.
[X] Bug Fix  
[ ] Refactor  
=> Fix odata startswith and endswith filters

backend/pkg/database/odatasql/query.go, backend/pkg/database/odatasql/query_test.go, backend/pkg/database/odatasql/schema.go
With this change if you put a field in $filter or $orderby which requires expansion, the underlying query will expand it. This works regardless of whether the field is $expand in the returned data.
[ ] Bug Fix  
[ ] Refactor  
=> Make filter and orderby work for fields that need to be expanded

installation/aws/VmClarity.cfn, runtime_scan/pkg/config/aws/config.go, runtime_scan/pkg/provider/aws/client.go
This exposes a new environment variable configuration AWS_INSTANCE_TYPE for the orchestrator which configures the instance type to use for the scanner VMs. It defaults to t2.large.
A new parameter has been added to the cloud formation to allow user's to choose which instance type they wish to use at install time.
[ ] Bug Fix  
[ ] Refactor  
=> Make AWS Scanner VM InstanceType configurable

installation/aws/VmClarity.cfn
This PR removes the SSH ingress rule from the ScannerSecurityGroup to prevent circular dependencies between the created resources in AWS. Without this change its not possible to delete the SecurityGroups because they have rules which reference each other.
[X] Bug Fix  
[ ] Refactor  
=> Separate Ingress rules from Scanner SG in cloudformation

installation/aws/VmClarity.cfn
This change tweaks the init configs for VMClarity server so that cfn-hup and cfn-init hooks restart the services correctly when the cloud formation stack updates the VMClarity server configuration.
Without this change the cfn-hup and cfn-init notice the change and update the systemd unit files, but the services don't get restarted so they continue to run the old version.
This change also lowers the cfn-hup polling time from 15 minutes to 5 minutes, so that the VMClarityServer notices that the cloudformation has been updated sooner.
[X] Bug Fix  
[ ] Refactor  
=> Update VMClarity init so stack upgrades apply correctly

ui/src/layout/AssetScans/AssetScanDetails.js, ui/src/layout/AssetScans/TabAssetScanDetails.js, ui/src/layout/Findings/Exploits/ExploitDetails.js, ui/src/layout/Findings/Malware/MalwareDetails.js, ui/src/layout/Findings/Misconfigurations/MisconfigurationDetails.js, ui/src/layout/Findings/Packages/PackageDetails.js, ui/src/layout/Findings/Rootkits/RootkitDetails.js, ui/src/layout/Findings/Secrets/SecretDetails.js, ui/src/layout/Findings/Vulnerabilities/VulnerabilityDetails.js, ui/src/layout/detail-displays/AssetDetails/index.js, ui/src/layout/detail-displays/ScanDetails/index.js
=> UI drilldown modifications

ui/src/layout/Dashboard/RiskiestRegionsWidget/index.js
adding sorting to the riskiest regions widget
[ ] Bug Fix  
[ ] Refactor  
=> adding sorting to the riskiest regions widget

runtime_scan/pkg/cloudinit/cloudinit_template.go
Currently the CLI writes reports to the console by default which might make sense when the CLI is used locally. However it makes hard to spot issues/errors at runtime for scanner jobs as it pollutes the logs with the reports of the scanners.
This change makes the the scanner job to write the scanner reports to files at path provided via `--output` command line parameter.
[ ] Bug Fix  
[x] Refactor  
=> Make CLI write reports to file for scanner jobs

api/models/helpers.go, cli/cmd/root.go, cli/pkg/cli/cli.go, cli/pkg/state/local.go, cli/pkg/state/manager.go, cli/pkg/state/vmclarity.go, docs/testplans/abort-scan.md, runtime_scan/pkg/orchestrator/orchestrator.go, runtime_scan/pkg/orchestrator/scanwatcher/watcher.go, runtime_scan/pkg/scanner/job_managment.go, shared/pkg/families/manager.go
* Add `ScanWatcher` to look up for Scans which status has changed to `Aborted` and updated all the corresponding `ScanResult` status to `ABORTED` so the Scanner Worker and the CLI could detect cancellation events.
* Update Scanner Worker to detect if the `ScanResult `state is changed to `Aborted`.
[ ] Bug Fix  
[ ] Refactor  
[ ] Other (please describe)  
Manual steps to test aborting ongoing scans in live environment.
<details>
<summary>Expand</summary>
Create Scan Configuration file
```shell
cat <<EOF > scanconfig.json
{
"name": "test",
"scanFamiliesConfig": {
"sbom": {
"enabled": true
},
"vulnerabilities": {
"enabled": true
},
"exploits": {
"enabled": true
}
},
"scheduled": {
"cronLine": "0 */4 * * *",
"operationTime": …
```
=> Add support for stopping Scans to Orchestrator

shared/pkg/families/rootkits/chkrootkit/chkrootkit_test.go
This is causing random failures locally and in CI because it is configured to sort the wrong object type.
[X] Bug Fix  
[ ] Refactor  
=> Fix slice sort in chkrootkit unit test

installation/aws/VmClarity.cfn
When you deploy a cloud formation stack, even if you leave the default parameters the values are saved.
When you upgrade the saved values are used instead of the defaults, which means that if we change the container version in the default for a parameter it gets ignored on upgrade.
This commit changes the symantics of the parameters to overrides, only if provided will they override the value which we set in the CFN template. This means that:
- if you want to return to the default value you can delete the contents of the parameter.
- during upgrades the cloud formation will template in the new values unless an override is provided.
[X] Bug Fix  
[X] Refactor  
=> Handle upgrade of cloud formation with different defaults

installation/aws/VmClarity.cfn
Proposal to include a root volume definition in the Cloudformation template to increase the root volume size(from the default 8Gb) of the VMClarity Server to avoid very quickly running out of disk space when performing scans. Proposed increase to 30 Gb which is the max free tier limit.
[ ] Bug Fix  
[ ] Refactor  
[ x] Other (please describe)  
Minor enhancement suggestion to avoid users rapidly running out of disk space on the VM clarity Server when performing scans. 
- [ x] I have read the [contributing guidelines](/CONTRIBUTING.md)
- [ x] Existing issues have been referenced (where applicable)
- [x ] I have verified this change is not present in other open pull requests
- [n/a ] Functionality is documented
- [ x] All code …
=> increase root vol size

cli/cmd/root.go, cli/cmd/root_test.go, cli/pkg/presenter/writer.go, shared/pkg/families/malware/config.go, shared/pkg/families/malware/family.go, shared/pkg/families/malware/family_test.go, shared/pkg/families/misconfiguration/family.go, shared/pkg/families/misconfiguration/family_test.go, shared/pkg/families/misconfiguration/types/config.go, shared/pkg/families/rootkits/config.go, shared/pkg/families/rootkits/family.go, shared/pkg/families/rootkits/family_test.go, shared/pkg/families/secrets/config.go, shared/pkg/families/secrets/family.go, shared/pkg/families/secrets/family_test.go, shared/pkg/families/utils/utils.go, shared/pkg/families/utils/utils_test.go, shared/pkg/families/vulnerabilities/family.go, ui_backend/pkg/rest/dashboard_findings_impact_test.go
add a configuration option to the family config, that indicates whether the input path should be cleaned from the results. This is in order to not show the mount path in the results, but only the actually path on disk.
[* ] Bug Fix
=> remove mount prefix

installation/aws/VmClarity.cfn
exploit-db-server is a container that includes both the server and the updater logic in one. Use that container instead of carrying all the logic in the cloud formation.
[ ] Bug Fix  
[X] Refactor  
=> Use exploit-db-server instead of go-exploitdb + script

cli/cmd/root.go, cli/pkg/cli/cli.go, cli/pkg/presenter/default.go, cli/pkg/presenter/multi.go, cli/pkg/presenter/presenter.go, cli/pkg/presenter/vmclarity.go, cli/pkg/state/local.go, cli/pkg/state/manager.go, cli/pkg/state/vmclarity.go, shared/pkg/families/manager.go
Export scan results when family finish scanning, and not after all family scan is completed like today. 
This will make the scan progress more informative and granular. Also mark in progress for each family scan
[* ] New Feature
=> export results per family scan

installation/aws/VmClarity.cfn
Load backend container image and log level configuration from separate environment file in service unit to avoid reloading `systemd` daemon whenever the backend configuration is changed.
[ ] Bug Fix  
[x] Refactor  
=> Add separate backend configuration to CF template

runtime_scan/pkg/orchestrator/common/queue.go, runtime_scan/pkg/orchestrator/common/reconciler.go
This commit adds an option for an item to be enqueued after a specified
duration. During that duration the item can not be enqueued if requested
through Enqueue to ensure that the item is not enqueued before that
duration is completed.
This allows reconcilers to delay reconciliation for an item when it
knows it will be performing an operation which takes longer than the
polling cycle preventing the poller from requeuing that item.
RequeueAfter is a wrapper around Done() followed by EnqueueAfter() done
under the same lock to prevent race condition when an item could be
requeued between Done and the EnqueueAfter call.
Also adds a new error type, RequeueAfterError, which can be returned by
a reconcile function to indicate that an item should be requeued after a
certain duration. This should …
=> Add EnqueueAfter and RequeueAfter option to queue

api/openapi.yaml
`api/openapi.yaml` was missing `operationId` attributes for operationsObjects (documentation [here](https://spec.openapis.org/oas/v3.0.0#operationObject)).
oapi-codegen seems to ignore this and generates the operationId's if they are absent. I added the identifiers to match the ones generated by oapi-codegen, so there are no changes in the generated `client/model/server.gen.go`. I confirmed this by running `make api` and diffing the files.
Code generation tested with [openapi-python-generator](https://pypi.org/project/openapi-python-generator/).
Also ran the `make build` and `make test` to check for any failures, but no functionality has been changed.
[x] Bug Fix  
[ ] Refactor  
=> chore: Added operationId for operationObjects in OpenAPI specs

api/client/client.gen.go, api/models/models.gen.go, api/openapi.yaml, api/server/server.gen.go, backend/pkg/database/gorm/common.go, backend/pkg/database/gorm/odata.go, backend/pkg/database/gorm/scan.go, backend/pkg/database/gorm/scan_config.go, backend/pkg/database/gorm/scan_result.go, backend/pkg/database/gorm/scan_test.go, backend/pkg/database/gorm/target.go, backend/pkg/database/types/database.go, backend/pkg/rest/scan_config_controller.go, backend/pkg/rest/scan_controller.go, backend/pkg/rest/scan_result_controller.go, backend/pkg/rest/target_controller.go, shared/pkg/backendclient/client.go
This adds a revision number to every VMClarity API object, this number can be used as an eTag in the API through the If-Match header to ensure that we avoid "lost update" issues while reconciling objects.
[ ] Bug Fix  
[ ] Refactor  
=> Add revision number to VMClarity objects and support for If-Match header

backend/pkg/database/odatasql/jsonsql/postgres.go, backend/pkg/database/odatasql/jsonsql/sqlite.go, backend/pkg/database/odatasql/jsonsql/variant.go, backend/pkg/database/odatasql/query.go, backend/pkg/database/odatasql/query_test.go
This commit ensures that while building the json objects for select and expand, we cast the extracted data to json to avoid issues where the DB gets confused between JSON encoded strings and JSON data.
Without this change we sometimes get unexpected escaped quotes in the returned data as the DB thinks its been given a string, but its actually a json encoded string.
[X] Bug Fix  
[ ] Refactor  
=> Ensure we cast to JSON while build JSON objects

runtime_scan/pkg/orchestrator/scanresultwatcher/watcher.go
Fix API query used for fetching `ScanResult`(s) which need to be reconciled by `ScanResultWatcher` controller.
[x] Bug Fix  
[ ] Refactor  
=> fix: query for ScanResults to be reconciled

runtime_scan/pkg/orchestrator/scanresultprocessor/processor.go
Fix `ScanResult` status being hard-coded in the query used by `ScanResultProcessor` to fetch `ScanResult`(s) for findings processing.
[x] Bug Fix  
[ ] Refactor  
=> fix: query for fetching ScanResults in Processor

ui/src/layout/AssetScans/StatusIndicator/index.js
Fix `StatusMapping` for `ScanResults` in the UI which broken due to #379.
[x] Bug Fix  
[ ] Refactor  
=> fix(ui): ScanResult status mapping

backend/pkg/database/gorm/database.go, ui_backend/api/models/findingType.go, ui_backend/pkg/rest/dashboard_findings_trends.go
There was a need to improve the load time of the trends widget.
This PR improve it by
1. Adding an index for Trends widget query
2. Run the findings type queries in parallel
After testing, the full call for `/ui/api/dashboard/findingsTrends` improved from 6.5s to 300ms
[ ] Bug Fix  
[X] Refactor  
=> Optimize Trends widget load time

runtime_scan/pkg/provider/aws/client.go, runtime_scan/pkg/provider/aws/helpers.go, runtime_scan/pkg/provider/aws/types.go
Fix AWS provider kind to use `models.AWS`.
Fixes: [#391](https://github.com/openclarity/vmclarity/issues/391), [#394](https://github.com/openclarity/vmclarity/issues/394)
[x] Bug Fix  
[ ] Refactor  
=> fix(aws): incorrectly set AWS provider kind

runtime_scan/pkg/orchestrator/scanwatcher/watcher.go
Fix patching aborted scans by adding only the updated fields to the `PATCH` request.
[x] Bug Fix  
[ ] Refactor  
=> fix: patching aborted scan

runtime_scan/pkg/orchestrator/common/event.go, runtime_scan/pkg/orchestrator/common/poller.go, runtime_scan/pkg/orchestrator/common/queue.go, runtime_scan/pkg/orchestrator/common/queue_test.go, runtime_scan/pkg/orchestrator/common/reconciler.go, runtime_scan/pkg/orchestrator/scanconfigwatcher/event.go, runtime_scan/pkg/orchestrator/scanconfigwatcher/watcher.go, runtime_scan/pkg/orchestrator/scanresultprocessor/processor.go, runtime_scan/pkg/orchestrator/scanresultwatcher/event.go, runtime_scan/pkg/orchestrator/scanresultwatcher/watcher.go, runtime_scan/pkg/orchestrator/scanwatcher/event.go, runtime_scan/pkg/orchestrator/scanwatcher/watcher.go
* extend `ReconcileEvent` interface with `Hash` function returning `string` type which does implement the `comparable` interface required by `map` for types used as keys.
* change `common.Queue` to rely on the `ReconcileEvent` type instead of `comparable` to provide more flexibility on how  the items pushed to the queue are compared to eachother avoiding duplicated items on the queue.
* add logging of the items being pushed to the queue or popped from the queue for reconciling.
[ ] Bug Fix  
[x] Refactor  
=> refactor: reconcile event

backend/pkg/backend/backend.go, docs/configuration.md, installation/aws/VmClarity.cfn, runtime_scan/pkg/orchestrator/config.go, runtime_scan/pkg/orchestrator/orchestrator.go, runtime_scan/pkg/orchestrator/scanresultwatcher/config.go, runtime_scan/pkg/orchestrator/scanresultwatcher/helpers.go, runtime_scan/pkg/provider/aws/client.go, runtime_scan/pkg/provider/aws/config.go, runtime_scan/pkg/provider/aws/config_test.go, runtime_scan/pkg/provider/types.go
* removed `Provider` specific configuration form `orchestrator.Config`
* added `VMCLARITY_AWS` prefix to environment variables related to `aws` package
* switch from using `viper.Get*` getters to `viper.Unmarshal` to initialize `aws.Config`
* extended documentation with the configuration options for `Orchestrator` and `Provider` components.
[ ] Bug Fix  
[x] Breaking Change  
[x] Refactor  
=> refactor: provider configuration

installation/aws/VmClarity.cfn
This leaves the well tested and working SQLite DB driver as the default and only option to install VMClarity with.
Postgres options will be re-enabled once the Postgres driver issues are resolved.
[ ] Bug Fix  
[ ] Refactor  
=> Postgres DB driver has issues so removing the option to configure it

.github/workflows/reusable-build-and-push.yml, Dockerfile.backend
The multiarch Docker image doesn't work on crosscompiled platforms (arm64 in this case because we build on amd64).
With this PR merged in, it will work on amd64 and arm64 as well.
After a couple days of digging, I ended up using the following repository: https://github.com/tonistiigi/xx
This is an utility image that helps installing the proper cross compiling tools for the target platform.
[x] Bug Fix  
[ ] Refactor  
=> fix: multiarch docker image

README.md, installation/azure/vmclarity-UI.json, installation/azure/vmclarity-install.sh, installation/azure/vmclarity.bicep, installation/azure/vmclarity.json, installation/azure/vmclarityDeployModule.bicep, installation/azure/vmclarityDiscoverRole.bicep, installation/azure/vmclarityManagedIdentity.bicep, installation/azure/vmclarityScanRole.bicep
Introduces an installer for VMClarity on Azure using Bicep / Azure Resource Manager. VMClarity will be installed into a new Resource Group with the control plane services running in a single VM. A dedicated VMClarity vNet will be created with 2 subnets, one for the control plane services which allows external access to the VMClarity server, and one for the Scanners which is only allows ingress from the control plane network so that it can be used as a bastion.
Two roles are added:
- One for discovery and snapshotting within a subscription.
- One for creating resources within the VMClarity resource group for scanning (VM, Disks, Network Interfaces)
To install on Azure you can either:
- use the az CLI to directly deploy the bicep (vmclarity.bicep)
- manually upload the ARM template …
=> Installer for VMClarity on Azure

Dockerfile.backend
Add mount type cache to go build command in Dockerfile.backend.
[ ] Bug Fix  
[ ] Refactor  
=> feat(dockerfile): add mount type cache to go build command

runtime_scan/pkg/provider/cloudinit/cloud-init.tmpl.yaml, runtime_scan/pkg/provider/cloudinit/testdata/cloud-init.yaml
Containers can only be aware of device mount points which are within their containerized filesystem. This means that if a device is mounted somewhere on the host, and that location on the host is not exposed to the container, the container can not determine if its mount or not.
This commit resolves this issue by making the whole host filesystem available for the container to see by mounting it into a sub-directory called `/hostfs` within the containers filesystem.
Once the container can see the host filesystem, all volumes which are mounted by the host or by the scanner have a mount point defined in `lsblk`.
Note that by …
=> fix: Volume mount scanner host fs into scanner container

ui/src/layout/Assets/AssetsTable.js, ui/src/layout/detail-displays/Findings/index.js
Ensures the data is pulled from the API for the summaries to be displayed in the assets table.
Ensures that assets with missing summary data don't crash the UI when in the assets drill down, without this change it just displays a blank screen.
[X] Bug Fix  
[ ] Refactor  
=> fix: Fix summaries in the asset table and asset details

runtime_scan/pkg/orchestrator/config.go, runtime_scan/pkg/orchestrator/scanresultwatcher/config.go, runtime_scan/pkg/orchestrator/scanresultwatcher/watcher.go
The `vmclarity-cli` running on the `Scanner` instance is responsible for handling the `aborted` event for the corresponding `ScanResult`. The `ScanResultWatcher` controller will periodically check whether the `vmclarity-cli` managed to gracefully shutdown the running scan and set the` ScanResult `to `done` indicating that thr scan is finished and the Scanner instance could be removed. However moving the `ScanResults` state to `done` will not happen in case the `vmclarity-cli` process is not running on the Scanner instance making the `ScanResultWatcher` controller waiting indefinitely.
The `ScanResultWatcher` will now monitor the `ScanResults` in `aborted` state and will move their state to `done` after a predefined period of time.
[x] Bug Fix  
[x] …
=> fix: ScanResults stuck in aborted state

installation/aws/VmClarity.cfn
I updated the Ubuntu images from 20.04 LTS to 22.04 LTS.
I changed the python `easy_install` to `pip3` because the `easy_install` does not work on newer Ubuntu version.
[ ] Bug Fix  
[ ] Refactor  
=> feat: update ubuntu server in cloudformation to 22.04 LTS

runtime_scan/pkg/orchestrator/assetscanwatcher/config.go, runtime_scan/pkg/orchestrator/config.go, runtime_scan/pkg/orchestrator/scanconfigwatcher/config.go, runtime_scan/pkg/orchestrator/scanwatcher/config.go
The current 1 minute results in multi-minute start up times for a scan because it has to reconcile multiple times to step through Pending -> Discovered -> InProgress.
[ ] Bug Fix  
[ ] Refactor  
[X] Other (please describe)  optimisation
=> feat: Reduce default orchestrator poller interval to 15 seconds

backend/pkg/database/gorm/database.go, backend/pkg/database/odatasql/jsonsql/postgres.go, installation/aws/VmClarity.cfn, installation/azure/vmclarity.bicep, installation/azure/vmclarity.json
* Removes any timestamp casting from the indexes, these aren't allowed to be part of an expression index in postgres.
* Ensures that null values are handled correctly by JSONB_EACH_ARRAY. The postgres function expect the data must be an array, so we need to detect any other types in the SQL statement and switch it to empty array.
[X] Bug Fix  
[ ] Refactor  
=> fix: Fix issues with postgres DB support

installation/aws/VmClarity.cfn
Updated control plane elements to newest image.
Added arm AMI images to the instance type mapping.
Fixed a bug: the scanner image id is inferred from the control plane instance type.
[x] Bug Fix  
[ ] Refactor  
=> feat(cfn): add arm64 support for controlplane

README.md, installation/gcp/dm/.flake8, installation/gcp/dm/.gitignore, installation/gcp/dm/Makefile, installation/gcp/dm/README.md, installation/gcp/dm/components/cloud-router.py, installation/gcp/dm/components/firewall-rules.py, installation/gcp/dm/components/network.py, installation/gcp/dm/components/roles.py, installation/gcp/dm/components/service-account.py, installation/gcp/dm/components/static-ip.py, installation/gcp/dm/components/vmclarity-install.sh, installation/gcp/dm/components/vmclarity-server.py, installation/gcp/dm/components/vmclarity-server.py.schema, installation/gcp/dm/components/vmclarity_install_script.py, installation/gcp/dm/components/vmclarity_install_script.py.schema, installation/gcp/dm/pyproject.toml, installation/gcp/dm/vmclarity-config.example.yaml, installation/gcp/dm/vmclarity.py, installation/gcp/dm/vmclarity.py.schema
This commit adds GCP Cloud Deployment Manager as a new method for installing VMClarity.
[ ] Bug Fix  
[ ] Refactor  
=> feat: Add GCP installer using GCP Deployment Manager

pkg/backend/database/odatasql/query.go, pkg/backend/database/odatasql/query_test.go
The any() lamdba operator can be used like:
GET api/Targets?$filter=findingInfo/tags/any(t: t/Key eq 'Name' and t/Value eq 'vmclarity-server')
This will return all Targets with at least one tag which has Key Name and the Value vmclarity-server.
The all lamba operator can be used like:
GET api/Targets?$filter=findingInfo/securityGroups/all(g: g/id eq 'sg1' or g/id eq 'sg2')
This will return Targets which are only in the security groups sg1 and sg2, no other security groups.
The not operator can be used like:
GET api/Targets?$filter=not(startswith(location, 'us-east-2'))
This will return all Targets which do not have a location which starts with us-east-2.
[ ] Bug Fix  
[ ] Refactor  
=> Add support for any, all and not ODATA operators

pkg/shared/families/utils/utils.go
Fix size cache to save by input instead of input type
[* ] Bug Fix  
[ ] Refactor  
=> fix: benchmark cache map by input instead of input type

installation/azure/vmclarity.bicep, installation/azure/vmclarity.json, installation/azure/vmclarityDeployModule.bicep, installation/docker/dockercompose.yml, installation/docker/image_override.env, installation/gcp/dm/components/vmclarity-server.py.schema, installation/gcp/dm/vmclarity.py.schema
VMClarity UI backend is built and published as vmclarity-ui-backend, there are a few places refering to it as vmclarity-uibackend. This commit fixes these references to use the dashed version.
[X] Bug Fix  
[ ] Refactor  
=> fix: vmclarity-ui-backend references

docs/command_line.md, docs/scanConfig.json, docs/test_e2e.md, docs/testplans/abort-scan.md
Update documentation to reflect the latest changes:
* Change api url from `http://localhost:8888/api` to `http://localhost:8080/api`
* Change scan config example to match new `ScanConfig` struct
[ ] Bug Fix  
[ ] Refactor  
=> docs: update api url and scan config example

.golangci.yml, pkg/orchestrator/assetscanwatcher/watcher.go, pkg/shared/families/exploits/family.go, pkg/shared/families/sbom/family.go, pkg/shared/fsutils/lsblk/internal/scan.go, pkg/uibackend/rest/dashboard_findings_impact.go
This PR enable 2 linter and fix the related warnings for this issue:
https://github.com/openclarity/vmclarity/issues/364
[ ] Bug Fix  
[ X ] Refactor  
[ ] Other (please describe)  
- [ X ] I have read the [contributing guidelines](/CONTRIBUTING.md)
- [ X ] Existing issues have been referenced (where applicable)
- [ X ] I have verified this change is not present in other open pull requests
- [ X ] Functionality is documented
- [ X ] All code style checks pass
- [ X ] New code contribution is covered by automated tests
- [ X ] All new and existing tests pass
=> Re-enable dupword and wastedassign linter

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, README.md, docs/test_e2e.md
The contributing link is broken in the PR template as mentioned here: https://github.com/openclarity/vmclarity/issues/546
This PR is fixing this link to the correct one and remove some unnecessary slash from other docs.
[ X ] Bug Fix  
[ ] Refactor  
[ ] Other (please describe)  
- [ X ] I have read the [contributing guidelines](/CONTRIBUTING.md)
- [ X ] Existing issues have been referenced (where applicable)
- [ X ] I have verified this change is not present in other open pull requests
- [ X ] Functionality is documented
- [ X ] All code style checks pass
- [ X ] New code contribution is covered by automated tests
- [ X ] All new and existing tests pass
=> Clean up links in the docs

pkg/apiserver/database/odatasql/query.go
This PR downgrade the log level to debug in sourceFromQueryPath because it is too noisy in production enviroment as mentioned here: https://github.com/openclarity/vmclarity/issues/521
Otherwise for debugging this log can be useful and easier to search for the queryPath with cli tools like grep.
[ X ] Bug Fix  
[ ] Refactor  
[ ] Other (please describe)  
- [ X ] I have read the [contributing guidelines](/CONTRIBUTING.md)
- [ X ] Existing issues have been referenced (where applicable)
- [ X ] I have verified this change is not present in other open pull requests
- [ X ] Functionality is documented
- [ X ] All code style checks pass
- [ X ] New code contribution is covered by automated tests
- [ X ] All new and existing tests pass
=> Downgrade the QueryPath log to debug level

.golangci.yml
Increase golangci-lint timeout to avoid blocking the CI pipeline intermittently.
[ ] Bug Fix  
[ ] Refactor  
=> ci: increase lint timeout

cmd/vmclarity-apiserver/main.go, cmd/vmclarity-orchestrator/main.go, cmd/vmclarity-ui-backend/main.go, installation/docker/dockercompose.yml, pkg/apiserver/apiserver.go, pkg/apiserver/config.go, pkg/orchestrator/config.go, pkg/orchestrator/orchestrator.go, pkg/uibackend/config.go
https://github.com/openclarity/vmclarity/issues/547
- Small refactor on apiserver to improve consistency with other services (move default configs to config file)
- Add healthz endpoint to orchestrator service and healthcheck to its container
- Add healthz endpoint to ui backend service and healthcheck to its container
[ ] Bug Fix  
[ ] Refactor  
=> feat: add healthz check to orchestrator and to ui backend

Makefile
The `golangci-lint` does not support monorepo type of projects with multiple Go packages which means that currently only  the root package is tested.
This change finds all the Golang packages in the repository and runs `golangci-lint` for each of them.
[ ] Bug Fix  
[ ] Refactor  
=> fix(lint): golangci-lint to test multiple modules

e2e/docker-compose.override.yml, pkg/uibackend/rest/server.go
Reduce background recalculation interval in uibackend because the healthcheck will fail intermittently with a timeout if the recalculation fails and needs a rerun. 
[x] Bug Fix  
[ ] Refactor  
=> fix(uibackend): reduce recalculation interval

e2e/basic_scan_test.go, pkg/apiserver/database/gorm/asset.go
While developing the E2E tests, I noticed that some container and image assets appeared more than once in the DB. This was due to a case mismatch in the ODATA filter when we check for asset uniqueness.
The check for asset is found in the basic test should now always succeed without filtering by terminated assets.
[x] Bug Fix  
[ ] Refactor  
=> fix(apiserver): change odata filter in check uniqueness for containers

.golangci.yml, Makefile, e2e/basic_scan_test.go
Fix `make lint-go` target to fail in case there are linter errors reported.
[x] Bug Fix  
[ ] Refactor  
=> fix(lint): failing linter for go modules

Makefile
The makefile target was publishing under the old vmclarity-uibackend
image name and not the updated vmclarity-ui-backend name. This commit
corrects this so that its consistent with the CI/CD published versions
of that container.
[ ] Bug Fix  
[ ] Refactor  
=> fix: Ensure push-docker-ui-backend publishes correct name

pkg/orchestrator/discovery/discoverer.go
https://github.com/openclarity/vmclarity/issues/447
[x] Bug Fix  
[ ] Refactor  
=> fix(orchestrator): skip mark terminated if asset found but patch failed

.golangci.yml, Makefile, pkg/apiserver/config.go, pkg/cli/utils/apimodel.go, pkg/orchestrator/config.go, pkg/uibackend/rest/dashboard_riskiest_assets.go
Bump `golangci-lint` version to `1.54.2`. The `depguard` and `tagalign` linters were added since `1.52.x` which are temporarily disabled as former seems to be usefull, but requires a discussion with the team before enabling it while, the latter does not seem to provide much of a value besides making the structs with struct tags a bit more readable/organized.
Also fixed a couple of linter errors reported by `gosec`.
[ ] Bug Fix  
[x] Refactor  
=> feat: bump golangci-lint version to 1.54.2

pkg/shared/families/secrets/gitleaks/gitleaks.go
Limit gitleaks scanned files to 50MB. TODO: make configurable
Closes #622
[X] Bug Fix  
[ ] Refactor  
=> Limit gitleaks scanned files to 50MB. TODO: make configurable

.github/workflows/ci.yml
This job can be used as the indicator that every required job succeeded by the branch protection rules. Adding this means we no longer need to update the branch protection rules every time we make a change to the workflow instead it can be completely controlled in the workflow by managing whether "Success" runs successful.
[ ] Bug Fix  
[ ] Refactor  
[X] Other (please describe)  CI/CD
=> Add success job to ci.yml which only runs if everything else succeeds

pkg/orchestrator/discovery/discoverer.go, pkg/orchestrator/provider/aws/client.go, pkg/orchestrator/provider/azure/client.go, pkg/orchestrator/provider/docker/client.go, pkg/orchestrator/provider/external/client.go, pkg/orchestrator/provider/gcp/client.go, pkg/orchestrator/provider/kubernetes/provider.go, pkg/orchestrator/provider/types.go
Resolve https://github.com/openclarity/vmclarity/issues/445
Modify DiscoverAssets interface to return a channel of assets instead of
a list. This lays the foundation to prevent us from keeping big chunks
of assets in memory.
In a future PR, all the providers should be updated to paginate fetching
assets from their downstream APIs and feed the channel.
[ ] Bug Fix  
[X] Refactor  
=> Buffered Asset Discovery

Makefile
When running end to end tests with `make e2e`, build all service images and use them for testing.
[ ] Bug Fix  
[ ] Refactor  
=> feat(test): build all services when running e2e tests

pkg/orchestrator/provider/aws/client.go
Changing data type of "errs" from channel to slice 
By using slice , there is no need for "for loop" for iterating channel, we can use slice directly in errors.Join(errs...) function
[x] Bug Fix  
[ ] Refactor  
=> Fixing issue for Incorrect use of errors.Join in aws/client.go #608

pkg/apiserver/database/gorm/odata.go, pkg/apiserver/database/odatasql/jsonsql/postgres.go, pkg/apiserver/database/odatasql/jsonsql/sqlite.go, pkg/apiserver/database/odatasql/jsonsql/variant.go, pkg/apiserver/database/odatasql/query.go, pkg/apiserver/database/odatasql/query_test.go, pkg/apiserver/database/odatasql/schema.go, pkg/orchestrator/assetscanestimationwatcher/helpers.go, pkg/orchestrator/scanconfigwatcher/watcher.go
The length function is used to get the length of a collection field as
part of a filter query. For example `$filter=length(assetIds) eq 5`.
This new filter is used to address an issue with the asset statistics query
as it needs to check to see if a list of errors is unset or empty.
[X] Bug Fix  
[ ] Refactor  
=> Add support for length() function in ODataSQL

go.mod, go.sum, pkg/orchestrator/provider/aws/scanestimation/estimate.go, pkg/orchestrator/provider/aws/scanestimation/estimate_test.go, pkg/orchestrator/provider/common/utils.go
In scan estimation, use extrapolation to find static scan time from scan size. 
[ ] Bug Fix  
[x] Refactor  
=> feat: extrapolate estimated scan time from scan size

.github/workflows/build-and-push-component.yaml, .github/workflows/ci.yml
Reverts #602 as it broke the publishing container images for multiple architectures. This removes the E2E testing from the CI pipeline which will be re-added in a followup PR.
[x] Bug Fix  
[ ] Refactor  
=> Revert "ci(test): add e2e tests to ci pipeline (#602)"

pkg/orchestrator/scanestimationwatcher/watcher.go
Currently, when ScanEstimation is timed out, we move its state to Aborted. 
This prevent it from ever going into Failed state and getting cleaned out.
This fix moves timeout scan estimation into Failed state (same as in Scan reconciler/watcher)
[ *] Bug Fix  
[ ] Refactor  
=> fix(scan estimation): reconcile timeout state to failed

.github/workflows/build-and-push-component.yaml, .github/workflows/ci.yml, .github/workflows/main-merge.yml, .github/workflows/release.yaml, .github/workflows/reusable-build-and-push.yml
* add `concurrency` to make sure that CI pipeline runs on the latest commit of the Pull Request while all the ongoing runs targeting previous state are cancelled
* remove unused `upload` parameter
* build container images for each platform in parallel
[ ] Bug Fix  
[x] Refactor  
=> feat(ci): improve CI pipeline

pkg/apiserver/database/gorm/odata.go
This PR adds the missing OData schema definitions for `DirInfo` and `PodInfo` because the openAPI definition contains these objects.
fixes: #738 
[x] Bug Fix  
[ ] Refactor  
=> fix: missing DirInfo and PodInfo OData schemas

pkg/apiserver/database/odatasql/query.go, pkg/apiserver/database/odatasql/query_test.go
Sometimes we want to be able to $filter on the complex fields not just the leaf fields within them for example checking if they are null. The recent change to the odata validation meant that these were getting rejected.
Closes #737
[X] Bug Fix  
[ ] Refactor  
=> fix(odatasql): Ensure that $filter works for complex types

.github/workflows/ci.yml, .github/workflows/reusable-build-and-push.yml, .github/workflows/reusable-end-to-end-testing.yml, .github/workflows/reusable-image-names.yml
* re-enable End-to-End testing in CI pipeline
* move image name generation into a reusable component
[ ] Bug Fix  
[ ] Refactor  
=> feat(ci): re-enable end-to-end testing

.github/workflows/image-cleanup.yml
* run workflow to clean up container images built for specific Pull Request
* schedule cleanup job for cleaning up old untagged and/or PR related container images pusblished to GHCR and older than 1 months
[ ] Bug Fix  
[ ] Refactor  
=> feat(ci): cleanup published dev container images

ui/src/layout/Assets/AssetsTable.js, ui/src/layout/Assets/utils.js, ui/src/layout/detail-displays/AssetDetails/index.js
Fixes the presentation of name and labels fields on the assets page.
Also fixes the presentation of name, image and platform fields on the asset details page.
The asset details page was throwing an uncaught react error on the asset details page when the asset type was ContainerInfo. This issue is also fixed with this PR.
Fixes: https://github.com/openclarity/vmclarity/issues/763
NOTE:
This PR is fixing the issue above but the code will remain easily breakable with changes made to the API.
A bigger refactor would be required to make it easier to maintain and less error prone to future changes.
For example:
- separate presentation and data loading logic
- handle different asset types separately
[x] Bug Fix  
[ ] Refactor  
[ ] …
=> Fix asset fields on UI

installation/aws/VmClarity.cfn, installation/azure/vmclarity-UI.json, installation/azure/vmclarity.bicep, installation/azure/vmclarity.json, installation/azure/vmclarityDeployModule.bicep, installation/docker/docker-compose.yml, installation/gcp/dm/components/vmclarity-server.py.schema, installation/gcp/dm/vmclarity.py.schema
following the fix in https://github.com/openclarity/exploit-db-server/pull/19 updating the version to the latest tag
=> faet: bump exploit-db-server version

installation/azure/vmclarity-UI.json
The azure deploy template was still using the old backend name in the advanced section where we should be able to override the defaults. This PR fixes it to use the new services (orchestrator, apiserver etc.)
[* ] Bug Fix  
[ ] Refactor  
=> fix: azure deploy template have wrong values as defaults

pkg/apiserver/database/gorm/common.go
The code in deleteById was not using the SQLVariant logic to switch between the Postgres and SQLite versions of JSON extract and JSON quote this resulted in a 500 error when deleting an object through the API.
This commit switches to use the SQLVariant variable to generate the correct SQL command to query the ID.
Closes #820
[X] Bug Fix  
[ ] Refactor  
=> fix(postgres): Ensure that we use the correct JSON sql for delete by ID

Makefile
Add make target for:
* installing Azure CLI
* installing Azure Bicep CLI
* installing CloudFormation CLI
* generating Bicep templates
* linting Bicep templates
[ ] Bug Fix  
[ ] Refactor  
=> feat: add installing tools to Makefile

Dockerfile.cli, pkg/cli/state/testdata/effective-config.json, pkg/orchestrator/assetscanwatcher/config.go, pkg/orchestrator/assetscanwatcher/families.go, pkg/orchestrator/config.go, pkg/shared/families/malware/clam/clam.go, pkg/shared/families/malware/yara/config/config.go, pkg/shared/families/malware/yara/yara.go, pkg/shared/families/misconfiguration/lynis/reportParser_test.go, pkg/shared/families/misconfiguration/lynis/scanner.go, pkg/shared/families/misconfiguration/lynis/testdb.go, pkg/shared/families/misconfiguration/lynis/testdb_test.go, pkg/shared/families/misconfiguration/types/config.go, pkg/shared/families/rootkits/chkrootkit/chkrootkit.go, pkg/shared/families/secrets/gitleaks/gitleaks.go
* bump `vmclarity-tools-base` to `v0.5.1` for CLI container image
* refactor families to:
* use executable names as default if the path for them is not provided in the families config
* always perform executable lookup before invoking them
* remove defaulting for binary paths from Orchestrator config
[ ] Bug Fix  
[x] Breaking Change  
[x] Refactor  
=> refactor: cli tools

rfc/template.md
Add RFC template which can be used for writing proposals, design documents for VMClarity.
[ ] Bug Fix  
[ ] Refactor  
=> docs: add RFC template

pkg/uibackend/rest/dashboard_riskiest_assets.go
https://github.com/openclarity/vmclarity/issues/817 
[x] Bug Fix  
[ ] Refactor  
=> fix(uibackend): add greater than 0 findings condition to get riskiest assets

ui/src/layout/Dashboard/FindingsTabsWidget/findings-tabs-widget.scss, ui/src/layout/Dashboard/FindingsTabsWidget/index.js
Fix for https://github.com/openclarity/vmclarity/issues/818
Add empty list indication to the findings impact and riskiest assets dashboard widgets. The type of the finding is not part of the message (e.g. `no results available for malwares`) as is it would require more refactor in the widget but we want to do bigger refactors in the whole ui so let's wait with that now.
[x] Bug Fix  
[ ] Refactor  
=> fix(ui): add empty list indication to dashboard widgets

ui/src/components/VulnerabilitiesDisplay/index.js
Fix value in VULNERABILITY_SEVERITY_ITEMS that prevented the page to load.
See this error message as reference:
[x] Bug Fix  
[ ] Refactor  
=> fix(ui): fix asset scans page not loading issue

ui/src/components/TabbedPage/index.js, ui/src/components/TablePage/index.js
Fixes https://github.com/openclarity/vmclarity/issues/802
The browser's back button didn't work when we opened any of the table view pages.
Use replace navigation for search param changes and redirections to fix this issue.
[x] Bug Fix  
[ ] Refactor  
=> fix(ui): use replace navigation when needed

pkg/shared/families/rootkits/chkrootkit/chkrootkit.go
Fallback to the default binary instead of failing if the path for the chkrootkit brinary is not set in the configuration. Fail only if the binary is not available on $PATH either.
[x] Bug Fix  
[ ] Refactor  
=> fix: chkrootkit binary detection

pkg/shared/families/misconfiguration/lynis/scanner.go, pkg/shared/families/misconfiguration/lynis/testdb.go
The `lynis show dbdir` command returns the path to the test database directory where the output string has a trailing newline character which is not removed before generating the path for the `tests.db` file. This results a bogus file path like `/usr/local/lynis/db /tests.db` and triggers an error as the `tests.db` file is not accessable.
This fix make sure that the command output is sanitized by removing leading/trailing whitespaces and the path is cleaned before using it to assemble the file path for `tests.db`.
Switch to `filepath` from `path` for working with filesystem paths as the latter is not meant to be used with OS filesystem paths.
Also rename `testdb` variable to `testDB` in order to make it aligned with Go naming convention.
[x] Bug Fix  
[ ] Breaking Change …
=> fix: lynis testDB path

ui/src/layout/Scans/Configurations/ConfigurationsTable/index.js, ui/src/layout/Scans/Scans/ScansTable.js
Fixes https://github.com/openclarity/vmclarity/issues/821
Rename "Asset Query" to "Scope" as requested in the related issue.
Screenshots:
[x] Bug Fix  
[ ] Refactor  
=> fix(ui): rename "Asset Query" to "Scope"

e2e/abort_scan_test.go, e2e/fail_scan_test.go, e2e/full_scan_test.go, e2e/helpers.go
Replace the default families scan test case with a full families scan test case. This PR is blocked and CI will fail until the issues with the rootkits, misconfigurations and malware families are fixed.
* Rootkit fix https://github.com/openclarity/vmclarity/pull/883
* Misconfiguration fix https://github.com/openclarity/vmclarity/pull/886
* Malware https://github.com/openclarity/vmclarity/pull/888 https://github.com/openclarity/vmclarity/pull/892
[ ] Bug Fix  
[x] Refactor  
=> test(e2e): replace default families scan with full families scan

installation/kubernetes/helm/vmclarity/templates/orchestrator/deployment.yaml
Make sure that addresses for auxiliary service like `exploitsdb` are correctly set in `Orchestrator` config when VMClarity is deployed using `helm`.
[x] Bug Fix  
[ ] Refactor  
=> fix(helm): address for services in Orchestrator config

.github/workflows/ci.yml, .github/workflows/release.yaml, .github/workflows/reusable-end-to-end-testing.yml, .github/workflows/reusable-verification.yml
Switch to `actions/cache@v3` for caching Go dependencies and build cache for better cache hit ratio.
[ ] Bug Fix  
[x] Refactor  
=> refactor(ci): go caching

.github/workflows/semantic-pr.yml
Make sure that workflow for linting PR title runs once as it is currently invoked twice due to having both `pull_request_target` and `pull_request` events set up as triggers.
[x] Bug Fix  
[ ] Refactor  
=> fix(ci): run PR linter once

ui/src/layout/Dashboard/CounterDisplay/index.js, ui/src/layout/Dashboard/index.js
Fix for: https://github.com/openclarity/vmclarity/issues/894
On the Dashboard menu the `Completed scans` widgets shows every scan not only the completed ones.
This PR fixes this issue by checking the scans for their state property.
[x] Bug Fix  
[x] Refactor  
=> fix(ui): calculate completed scans count correctly

installation/aws/VmClarity.cfn, installation/azure/vmclarity.bicep, installation/azure/vmclarity.json, installation/azure/vmclarityDeployModule.bicep, installation/gcp/dm/components/vmclarity-server.py.schema, installation/gcp/dm/vmclarity.py.schema
Freshclam mirror was bumped for all providers except Azure and GCP.
[x] Bug Fix  
[ ] Refactor  
=> chore(deps): use ghcr.io/openclarity/freshclam-mirror:v0.2.0

.github/workflows/semantic-pr.yml
Add missing `pull-request: write` permission to `semantic-pr` workflow.
[ ] Bug Fix  
[ ] Refactor  
=> ci: fix permission for PR linter workflow

.github/workflows/image-cleanup.yml
CI job responsible for removing stale dev container images requires a Personal Access Token to fetch images and their version from GH API.
[ ] Bug Fix  
[ ] Refactor  
=> ci: use PAT token for dev image cleanup

Makefile
Remove `v` prefix from Helm Chart `version` in order to conform `semver` spec.
[ ] Bug Fix  
[ ] Refactor  
=> build: strip v prefix from Helm Chart version

.github/workflows/image-cleanup.yml
Enable CI workflow for deleting stale images older than 7 days and after PRs are closed.
[ ] Bug Fix  
[ ] Refactor  
=> ci: enable dev image cleanup

.github/workflows/release.yaml
Fix go cache key for _Creating Artifacts_ job in Release workflow as it was pointing to the cache created for `api` package.
[ ] Bug Fix  
[ ] Refactor  
=> ci: fix go cache key in release workflow

.github/workflows/release.yaml, Makefile
* fix binary dependency targets for bundle builds (bicep, helm, release-notes)
* install ICU dependency for Bicep on Linux (GH Actions runner)
* use glob pattern for `cp` for copying source for bundles to overcome the difference of `cp`'s behavior on `macos` and `linux`.
* remove multi-line strings in Makefile as they are handled differently by `make` on `linux` and`macos`.
[x] Bug Fix  
[x] Refactor  
=> build: fix building bundles

.github/workflows/release.yaml
Remove installing `libicu-dev` as it is preinstalled on Ubuntu runners for Github Actions.
[ ] Bug Fix  
[ ] Refactor  
=> ci: remove installing ICU on runner

Makefile
Remove target dependency responsible for detecting git repo changes used for regenerating release notes whenever new commit is created as it does not work in CI.
Need to research a better way to detect local changes which work detect states to trigger re-run of release notes target in Makefile.
[ ] Bug Fix  
[ ] Refactor  
=> build: rm target dep for release note generation

.github/workflows/release.yaml
Make sure to fetch the whole git repository instead of a single commit which is the [default](https://github.com/actions/checkout#usage). Generating release notes require the whole git history be available.
[ ] Bug Fix  
[ ] Refactor  
=> ci: fetch full git history for release

Makefile
Make sure that the Scanner container image version is updated when releasing Docker Compose bundle.
[ ] Bug Fix  
[ ] Refactor  
=> build: fix Scanner image version in Docker bundle

.github/workflows/image-cleanup.yml
Add missing `vmclarity-orchestrator-dev` to scheduled image cleanup job.
[ ] Bug Fix  
[ ] Refactor  
=> ci: add missing orchestrator dev image to cleanup

installation/kubernetes/helm/vmclarity/templates/apiserver/deployment.yaml
Fix API server deployment configuration to point to use the correct address of the Postgres DB.
[x] Bug Fix  
[ ] Refactor  
=> fix(helm): PostgreSQL DB config for API Server

pkg/orchestrator/provider/gcp/provider.go
Fix a nil pointer error by guarding it with an if statement.
[x] Bug Fix  
[ ] Refactor  
=> fix(gcp): nil pointer exception

installation/kubernetes/helm/vmclarity/README.md, installation/kubernetes/helm/vmclarity/templates/gateway/deployment.yaml, installation/kubernetes/helm/vmclarity/templates/gateway/service-headless.yaml, installation/kubernetes/helm/vmclarity/templates/gateway/service.yaml, installation/kubernetes/helm/vmclarity/values.yaml
* support `NodePort` and `LoadBalancer` service types additionally to `ClusterIP`
* add headless service
[ ] Bug Fix  
[ ] Refactor  
=> feat(helm): add multiple service types to gateway

installation/docker/docker-compose.yml
https://openclarity.io/docs/vmclarity/getting-started/install-vmclarity/#access-ui
The UI is accessible in all platforms at http://localhost:8080/ except for Docker where we use http://localhost:80/.
* Change the port exposed on host to make Docker consistent with other platforms
[ ] Bug Fix  
[x] Refactor  
=> refactor(docker): change gateway port to 8080

e2e/full_scan_test.go, e2e/suite_test.go, e2e/testenv/docker/docker-compose.override.yml, e2e/testenv/docker/docker.go, e2e/testenv/types/types.go, pkg/shared/uibackendclient/client.go
https://github.com/openclarity/vmclarity/issues/751
* Change e2e tests to use gateway
* Add a uibackend client similar to backend client 
* Extend default scan test (which exports some non-zero vulnerability results) to test uibackend dashboards
[ ] Bug Fix  
[ ] Refactor  
=> test(uibackend): add e2e tests for ui backend 

rfc/end-to-end-type-safe-apis.md
Please read the RFC for more details [here](https://github.com/openclarity/vmclarity/blob/rfc-for-e2e-type-safety/rfc/end-to-end-type-safe-apis.md) or in the PR.
[ ] Bug Fix  
[ ] Refactor  
=> docs: add rfc for e2e type safety

installation/docker/docker-compose.yml
Pin Docker Compose schema version to `3.5` which includes all the features used the `docker-compose.yml` file.
[ ] Bug Fix  
[x] Refactor  
=> refactor: pin Docker Compose schema version

pkg/orchestrator/assetscanprocessor/exploits.go, pkg/orchestrator/assetscanprocessor/vulnerabilities.go, pkg/shared/findingkey/common.go, pkg/shared/findingkey/common_test.go, pkg/shared/findingkey/exploit.go, pkg/shared/findingkey/malware.go, pkg/shared/findingkey/misconfiguration.go, pkg/shared/findingkey/package.go, pkg/shared/findingkey/rootkit.go, pkg/shared/findingkey/secret.go, pkg/shared/findingkey/vulnerability.go, ui/src/layout/Dashboard/FindingsImpactWidget/index.js
https://github.com/openclarity/vmclarity/issues/890
* Refactor to make findings keys for different families more consistent
* Add new key that will be independent of where vulnerability/malware is found (e.g. package/path). Let me know if you have any suggestions to improve the naming here :)
before <img width="250" alt="exploits" src="https://github.com/openclarity/vmclarity/assets/46568597/956dd03f-1d59-4f6e-908c-00241fe1827d"> -> after <img width="250" alt="exploits" src="https://github.com/openclarity/vmclarity/assets/46568597/640ac28e-4e63-4c6d-888b-e7cef9a31f5c">
before <img width="250" alt="malware" src="https://github.com/openclarity/vmclarity/assets/46568597/9ca92a11-15cf-45bb-b30e-3fcdfc458a3d">  -> after <img width="250" alt="malware-after" …
=> fix(uibackend): repeated items in impact dashboard

e2e/go.mod, e2e/go.sum, go.mod, go.sum
Switch to the `go-viper` fork of the unmantained `mapstructure` package that fixes a bug.
[ ] Bug Fix  
[ ] Refactor  
=> chore(deps): use go-viper fork of mapstructure

.github/workflows/build-and-push-component.yaml, .github/workflows/release.yaml
Bump `actions/upload-artifact` and `actions/download-artifact` to `v4` using the following [migration guide](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md) as the new version has breaking changes.
[ ] Bug Fix  
[ ] Refactor  
=> ci: bump action for artifact upload/download

.gitignore, CONTRIBUTING.md
Added `go.work*` files to gitignore, and docs how to use a `go.work` file in the repo.
[ ] Bug Fix  
[ ] Refactor  
[X] Documentation  
=> chore: repo to work with local go.work file

pkg/shared/families/infofinder/sshtopology/scanner.go, pkg/shared/families/infofinder/sshtopology/scanner_test.go
This PR fixes the `sshTopology` scanner's error, that failed when there was no `home` directory in the scanned filesystem.
before:
after:
[x] Bug Fix  
[ ] Refactor  
=> fix(cli): don't return error if home dir doesn't exist

rfc/multiple-go-modules.md
Add RFC to propose a new project structure which splits the main module into multiple modules to allow us to version modules separately and reduce dependencies.
[ ] Bug Fix  
[ ] Refactor  
=> docs: multiple go modules rfc

rfc/extend-misconfiguration-scanners.md
This PR includes an RFC that aims to:
- extends necessary logic to enable generic misconfiguration scanning capabilities, in order to
- provide a simple way to migrate CIS Docker Benchmark scanner from KubeClarity
[ ] Bug Fix  
[ ] Refactor  
=> docs: extend misconfiguration scanners rfc

README.md
Update cfn quick-create link in README file to latest release v0.6.0
[ ] Bug Fix  
[ ] Refactor  
=> docs(aws): update cfn quick-create link to latest release

ui/src/layout/detail-displays/AssetDetails/ContainerInfoDetails.jsx
Added the labels of a container to the ContainerInfo details page on the UI.
before:
after:
[ ] Bug Fix  
[ ] Refactor  
=> feat(ui): add label to ContainerInfo detail page

ui/src/layout/Scans/Scans/ScanActionsDisplay/index.jsx
Currently JavaScript PATCH-es a badly formatted body for aborting a `Scan`, this PR fixes this.
[x] Bug Fix  
[ ] Refactor  
=> fix(ui): abort scan from the ui

Makefile, e2e/suite_test.go
* make sure to run `go test ...` for all the modules in the repository
* use the `-short` flag for `go test` to exclude complex integration/end-to-end tests by default
[x] Bug Fix  
[ ] Refactor  
=> test: fix make test target

testenv/go.mod
Ad missing `repalce` for `api/client` to `testenv/go.mod`.
[x] Bug Fix  
[ ] Refactor  
=> fix(testenv): missing replace in go.mod

e2e/go.mod, testenv/go.mod
Fix missing `replace` statements in `e2e/go.mod` and `testenv/go.mod` files.
[x] Bug Fix  
[ ] Refactor  
=> fix: missing replace in go.mod

Makefile, docker-bake.hcl
Added Docker Bake to streamline docker builds, also modified the Makefile use bake for building and pushing images to the repository.
Modifying the CI will come in another PR.
Build time remained the same, but using Docker Bake comes with some advantages:
- from now on Dockerfiles can exist in any place, number, or name within the repo (or even remote URLs can be used); they can be referred to properly in `docker-bake.hcl` with the `context` and `dockerfile` fields
- multiple images can be built at once via target groups
- Makefile is a bit cleaner now by not having to specify the same build commands per each image
Fixes #1085 
[ ] Bug Fix  
[X] Refactor  
=> feat: add docker bake

.github/workflows/reusable-verification.yml, .golangci.yml, Makefile, cli/pkg/families/malware/clam/util/clam_util_test.go
Configure `goheader` linter to check license headers
[ ] Bug Fix  
[ ] Refactor  
=> feat: configure goheader lint

.github/workflows/reusable-verification.yml, Makefile, makefile.d/20-tools.mk
* Modify `license-check` and `license-cache` in Makefile to run for multiple modules
* Add `gomod-vendor` in Makefile
[ ] Bug Fix  
[x] Refactor  
=> refactor: check licenses in multiple modules

.github/workflows/reusable-verification.yml, .gitignore
Update CI job to properly store `licensei.cache` files (stored next to each `go.mod` file) for validating licenses running `licensei`. 
[ ] Bug Fix  
[ ] Refactor  
=> ci: fix caching for license check

.dockerignore, ARCHITECTURE.md, README.md, TOUR.md, installation/aws/README.md
https://github.com/openclarity/vmclarity/issues/1187
Fix image paths changed in https://github.com/openclarity/vmclarity/pull/1164
[x] Bug Fix  
[ ] Refactor  
=> fix: path to images

renovate.json
Do not pin  docker image versions by digest for `latest` tags.
[ ] Bug Fix  
[ ] Refactor  
=> ci: fix setting docker digest for latest tag

renovate.json
Disable pinning docker images by digest.
[ ] Bug Fix  
[ ] Refactor  
=> ci: disable pinning docker images by digest

cli/families/exploits/family.go, cli/go.mod, cli/go.sum, core/to/to.go, testenv/go.mod, testenv/go.sum, testenv/utils/fanout/fanout_test.go
Remove `golang.org/x/exp` dependency by replacing functionality from `stdlib` or with custom helpers.
[ ] Bug Fix  
[x] Refactor  
=> refactor: rm golang.org/x/exp dependency

cli/families/rootkits/chkrootkit/utils/parser.go, cli/presenter/apimodel.go, core/to/to.go, core/to/to_test.go, uibackend/server/dashboard_findings_impact.go
Refactor `core/to` package by renaming helper functions and adding documentation to the source code.
[ ] Bug Fix  
[x] Refactor  
=> refactor: core/to pkg

installation/docker/docker-compose.yml, installation/kubernetes/helm/vmclarity/README.md, installation/kubernetes/helm/vmclarity/values.yaml
Remove container image pinning in docker-compose and helm chart.
[ ] Bug Fix  
[ ] Refactor  
=> chore: rm pinning container images by digest

Makefile
Remove wrong character from license-cache target.
[x] Bug Fix  
[ ] Refactor  
=> fix: license-cache target

.github/workflows/ci.yml
The `success` is skipped instead of failed when depending jobs defined in `needs` parameter are skipped/failed. Skipped `success` job treated the same way as if it was successful therefore CI proceeds with merging Pull Request in case it has  auto-merge enabled.
[ ] Bug Fix  
[ ] Refactor  
=> ci: fix success check

Dockerfile.apiserver, Dockerfile.cli, Dockerfile.cr-discovery-server, Dockerfile.orchestrator, Dockerfile.uibackend, Makefile, docker-bake.hcl, orchestrator/orchestrator.go, orchestrator/provider.go, orchestrator/providerv2.go, provider/v2/aws/discoverer/discoverer.go, provider/v2/aws/estimator/estimator.go, provider/v2/aws/provider.go, provider/v2/aws/scanner/scanner.go, provider/v2/azure/discoverer/discoverer.go, provider/v2/azure/estimator/estimator.go, provider/v2/azure/provider.go, provider/v2/azure/scanner/scanner.go, provider/v2/gcp/discoverer/discoverer.go, provider/v2/gcp/estimator/estimator.go, provider/v2/gcp/provider.go, provider/v2/gcp/scanner/scanner.go
Add skeleton for `provider/v2` package for reworked/optimized provider implementations for cloud environments while maintaining backward compatibility with the existing provider interface.
[ ] Bug Fix  
[ ] Refactor  
=> feat: provider v2

Makefile
* Add bake option to push multiarch images
* Remove `push-docker` target and replace it with a `DOCKER_PUSH` var
[ ] Bug Fix  
[ ] Refactor  
=> build: push multiarch images

renovate.json
Pin version of the Alpine container image version used for testing to avoid breaking E2E tests.
[ ] Bug Fix  
[ ] Refactor  
=> ci: pin Alpine image version for testing

Dockerfile.cli, installation/aws/VmClarity.cfn, installation/azure/vmclarity-UI.json, installation/azure/vmclarity.json, installation/azure/vmclarityDeployModule.bicep, installation/docker/docker-compose.yml, installation/docker/image_override.env, installation/gcp/dm/components/vmclarity-server.py.schema, installation/kubernetes/helm/vmclarity/README.md, installation/kubernetes/helm/vmclarity/values.yaml
Yara version installed in `yara-tools-server` and `vmclarity-cli` images must be the same to avoid compatibility issues.
[x] Bug Fix  
[ ] Refactor  
=> fix: yara tools

.github/workflows/reusable-verification.yml, Makefile
Add `go vet` to `check` target in makefile in order to perform additional check prior running `golangci-lint` or test in order to catch certain issues early on like compilation errors.
[ ] Bug Fix  
[ ] Refactor  
=> build: add go vet to checks

.github/workflows/release.yaml, cliff.toml
The latest version of `git-cliff` allows us to populate release notes with information from GitHub like:
* contributor for each PR
* list of new contributors
* adding link to the full changelog in the footer
[ ] Bug Fix  
[ ] Refactor  
=> build: improve release notes generation

installation/aws/VmClarity.cfn, installation/azure/vmclarity-UI.json, installation/azure/vmclarity.bicep, installation/azure/vmclarity.json, installation/azure/vmclarityDeployModule.bicep, installation/docker/docker-compose.yml, installation/docker/image_override.env, installation/gcp/dm/components/vmclarity-server.py.schema, installation/gcp/dm/vmclarity.py.schema, installation/kubernetes/helm/vmclarity/README.md, installation/kubernetes/helm/vmclarity/values.yaml
Update `freshclam-mirror` version to v0.3.1
[ ] Bug Fix  
[ ] Refactor  
=> fix(deps): bump freshclam-mirror to v0.3.1

Makefile
Add cleaning up go vendor directories to Makefile.
[ ] Bug Fix  
[ ] Refactor  
=> build: add cleaning up go vendor directories

.github/workflows/ci.yml, .github/workflows/reusable-verification.yml
Merge API and Helm documentation tests into Verification workflow for speeding up the CI runs.
[ ] Bug Fix  
[ ] Refactor  
=> ci: refactor verification job

Makefile
This PR fixes the `dist-vmclarity-cli` command in the `Makefile`, because it was broken.
It also switches the `cd` command for `-C` flag for `go build` `go test` and `go generate` commands.
[x] Bug Fix  
[x] Refactor  
=> fix: add -C flag to go commands in Makefile

Makefile, makefile.d/10-helpers.mk
Create a comma-separated list instead of a space-separated list from `GO_BUILD_TAGS` in the Makefile. The previous solution worked for go-related make targets (build, test, vet stc.) but was not sufficient for the `make docker*` targets.
[X] Bug Fix  
[ ] Refactor  
=> fix: subst spaces with commas in GO_BUILD_TAGS

workflow/internal/dispatcher/dispatcher.go, workflow/workflow_test.go
Fix race condition where certain cases goroutine is able to send task update to closed channel. 
[x] Bug Fix  
[ ] Refactor  
=> fix: race condition in workflow

Makefile
Fix passing Go build tags properly for Make targets running `go vet` and `go test`.
[ ] Bug Fix  
[ ] Refactor  
=> build: fix build tags for go vet and test

provider/v2/docker/config.go, provider/v2/docker/discoverer/container.go, provider/v2/docker/discoverer/discoverer.go, provider/v2/docker/discoverer/image.go, provider/v2/docker/estimator/estimator.go, provider/v2/docker/provider.go, provider/v2/docker/scanner/scanner.go
* Move Docker provider code to new provider V2 skeleton added with https://github.com/openclarity/vmclarity/pull/1299
* Tested manually with `GO_BUILD_TAGS=providerv2 make e2e` ✅ 
[ ] Bug Fix  
[x] Refactor  
=> refactor(docker): docker provider to provider v2

Makefile
Extend Makefile with targets for fixing Renovate version updates by running post update steps.
[ ] Bug Fix  
[ ] Refactor  
=> ci: add Make targets for fixing Renovate updates

.github/workflows/reusable-end-to-end-testing.yml, .github/workflows/reusable-verification.yml
Remove unused tools from GHA runners to avoid CI pipeline failures due to insufficient disk space.
```shell
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        73G   68G  4.5G  94% /                   <<< BEFORE
tmpfs           7.9G  172K  7.9G   1% /dev/shm
tmpfs           3.2G  1.1M  3.2G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/sda15      105M  6.1M   99M   6% /boot/efi
/dev/sdb1        74G  4.1G   66G   6% /mnt
tmpfs           1.6G   12K  1.6G   1% /run/user/1001
1.6G	/usr/share/dotnet
8.9G	/usr/local/lib/android
5.0G	/opt/hostedtoolcache/CodeQL
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        73G   53G   20G  73% /                  <<< AFTER
tmpfs           7.9G  172K  7.9G   1% /dev/shm
tmpfs           3.2G  1.1M  3.2G   1% /run …
```
=> ci: rm tools from runner to free up disk space

installation/aws/VmClarity.cfn, installation/docker/docker-compose.yml
Add healthchecks to the docker compose file in the Cloudformation template to make it consistent with https://github.com/openclarity/vmclarity/blob/main/installation/docker/docker-compose.yml.
Tested on AWS ✅ 
[ ] Bug Fix  
[ ] Refactor  
=> feat(aws): add healthz checks to cloudformation template

installation/gcp/dm/components/vmclarity-install.sh
This PR adds healthchecks to the docker containers that spin up when the system is installed on GCP.
[ ] Bug Fix  
[x] Refactor  
=> refactor(gcp): add healthcheck to GCP installer

api/server/database/gorm/asset.go
- Added a check if `asset.Id` is nil or empty, a 400 bad request error is returned.
Fixes: #707
[X] Bug Fix  
[ ] Refactor  
=> fix: Nil pointer error if `ContainerImageInfo.Id` field is not set

.github/workflows/reusable-end-to-end-testing.yml, .github/workflows/reusable-verification.yml
Move runner disk cleanup before restoring go cache.
[ ] Bug Fix  
[ ] Refactor  
=> ci: mv runner disk cleanup before cache restore

utils/fsutils/mount/unix.go
Fix custom `error` returned by `mount.Mount` and `mount.Umount` functions in `utils/fsutils/mount` pkg which returned the `error` by value instead of pointer. 
[x] Bug Fix  
[ ] Refactor  
=> fix: error returned by mount

e2e/dir_scan_test.go, e2e/testdata/go.mod, e2e/testdata/go.sum, e2e/testdata/test.go, provider/docker/provider.go
Currently, the docker provider is only capable of scanning images and containers.
* Extend docker provider to be able to scan an Asset directory
* Add e2e test
[ ] Bug Fix  
[ ] Refactor  
=> feat(docker): scan dir asset

api/types/assetscanstatus.go, orchestrator/watcher/scan/watcher.go, scanner/findingkey/rootkit.go
Fixed some bugs while testing, mainly around when a scan is being aborted:
- allow to transition from any status to aborted - I think this makes sense as sometimes aborting the scan is needed something is broken and some assetScans couldn't get to the `ReadyToScan` phase
- fix a race condition in the orchestrator - related log:
```shell
WARNING: DATA RACE
Write at 0x00c001bb8c40 by goroutine 9201:
github.com/openclarity/vmclarity/orchestrator/watcher/scan.(*Watcher).reconcileAborted.func1()
/build/orchestrator/watcher/scan/watcher.go:491 +0x238
Previous write at 0x00c001bb8c40 by goroutine 9200:
github.com/openclarity/vmclarity/orchestrator/watcher/scan.(*Watcher).reconcileAborted.func1()
/build/orchestrator/watcher/scan/watcher.go:491 +0x238
Goroutine 9201 (running) created at: …
```
=> fix: bugs around aborting scan

e2e/config/config.go, e2e/config/config_test.go, e2e/go.mod, e2e/go.sum, installation/gcp/dm/components/roles.py, installation/gcp/dm/components/vmclarity-install.sh, installation/manifests.go, testenv/config.go, testenv/gcp/asset/asset.go, testenv/gcp/config.go, testenv/gcp/gcp.go, testenv/gcp/utils.go, testenv/go.mod, testenv/go.sum, testenv/testenv.go, testenv/types/environment.go, testenv/utils/docker/docker.go, testenv/utils/ssh.go
This PR adds the GCP E2E test environment to the codebase.
[ ] Bug Fix  
[ ] Refactor  
=> feat: add gcp e2e test env

e2e/dir_scan_test.go
https://github.com/openclarity/vmclarity/issues/1599
Set `lastSeen` field to 10 min from now so the directory asset is not marked as terminated by the discoverer. 
Kudos to @adamtagscherer and @csatib02 for catching this issue 🎉 
[x] Bug Fix  
[ ] Refactor  
=> fix(e2e): set directory asset last seen to future time

cli/go.mod, cli/go.sum, orchestrator/go.mod, orchestrator/go.sum, provider/go.mod, provider/go.sum, scanner/families/misconfiguration/cisdocker/config.go, scanner/families/misconfiguration/cisdocker/report.go, scanner/families/misconfiguration/cisdocker/report_test.go, scanner/families/misconfiguration/cisdocker/scanner.go, scanner/go.mod, scanner/go.sum
The dockle package [has been updated](https://github.com/Portshift/dockle/pull/14) so the CIS docker scanner can be used with `rootfs` and `dir` type of assets as well!
Fixes #1376.
[ ] Bug Fix  
[ ] Refactor  
=> feat: CIS docker scanner to work with rootfs, dir

api/server/database/gorm/odata.go, api/server/database/odatasql/jsonsql/postgres.go, api/server/database/odatasql/jsonsql/sqlite.go, api/server/database/odatasql/jsonsql/variant.go, api/server/database/odatasql/query.go, uibackend/server/dashboard_riskiest_assets.go
https://github.com/openclarity/vmclarity/issues/1127
* Queries to get assets with `TotalExploits`, `TotalMalware`, etc were failing because the total value was not casted to integer. Therefore, implementation of cast to integer for Postgres is required.
* For `TotalVulnerabilities` instead of checking if this object property is greater than zero, we need to check the fields inside this object (`totalCriticalVulnerabilities`, `totalHighVulnerabilities`, etc).
* Fix `findingsProcessed` is boolean not integer in the ODATA schema
This fix was tested manually with the Docker provider using Postgres ✅ 
[x] Bug Fix  
[ ] Refactor  
=> fix: riskiest assets fails with postgres 

containerruntimediscovery/server/containerd/discoverer.go
When running a basic Kubernetes scan (SBOM + Vulnerabillities) on container images, asset scans fail with `failed to analyzer input "/mnt/snapshot/image.tar": failed to run job: failed to create source analyzer=syft: an error occurred attempting to resolve '/mnt/snapshot/image.tar': additionally, the following providers failed with file does not exist: oci-archive`.
Looking at the cr discovery server logs, the error is `content digest sha256:<hash>: not found`. 
This PR fixes this issue when an image is exported without providing a specific platform.
Please note that this does not fix the second error mentioned in the issue.
Tested manually on Kubernetes ✅ 
[x] Bug Fix  
[ ] Refactor  
=> fix: containerd export strictly matching platform

Makefile, e2e/abort_scan_test.go, e2e/basic_scan_test.go, e2e/config/config.go, e2e/config/config_test.go, e2e/dir_scan_test.go, e2e/fail_scan_test.go, e2e/full_scan_test.go, e2e/helpers.go, e2e/report.go, installation/kubernetes/helm/vmclarity/README.md, installation/kubernetes/helm/vmclarity/values.yaml, testenv/kubernetes/kind/dockerimageloader.go
Revisit kubernetes test environment and ensure that tests are successfully running on this provider.
* Fix images failing to load by using image name not image ID while saving image to load to node
* Define new params for the k8s environment
* Add target in Makefile to run e2e tests on Kubernetes
* Disable syft analyzer in kubernetes e2e tests due to scan failures when scanning container images https://github.com/openclarity/vmclarity/issues/1666 (second error reported)
* Enable misconfiguration family for Docker and Kubernetes (this change required an increase in scan timeout)
[x] Bug Fix  
[x] Refactor  
=> feat(e2e): revisit k8s test env

.github/workflows/ci.yml, .github/workflows/reusable-end-to-end-testing.yml, Makefile, testenv/kubernetes/kind/dockerimageloader.go
* Add new `make e2e-docker` target and use `make e2e` to run end to end tests on both Docker and Kubernetes
* Run end to end tests running on Kubernetes in the CI pipeline. This should not increase the CI pipeline run time significantly since Kubernetes tests (~15min) and Docker tests (~14min) will run in parallel.
* Required steps for merge in this repository need to be updated
[ ] Bug Fix  
[ ] Refactor  
=> ci: run k8s tests

Makefile
Temporary workaround to remove race flag from orchestrator build since build fails in arm64 after #1587 
[x] Bug Fix  
[ ] Refactor  
=> fix: remove race flag from orchestrator docker build

plugins/runner/internal/containermanager/docker/client.go, plugins/runner/internal/containermanager/docker/manager.go, plugins/runner/internal/containermanager/types.go, plugins/runner/runner.go, scanner/families/plugins/runner/runner.go
This PR creates a default plugin network to isolate all plugins from the rest of Docker services. Plugins will only be part of this network.
If running the CLI in container mode, the host container will be attached to the plugin network to allow DNS resolution of plugin container IDs used for communication.
Minor fix to plugin family logging to ensure that plugin metadata is displayed properly instead of pointer values.
IMPORTANT NOTE: Host container when running in container mode needs to have default hostname set by Docker to ensure that it can be detected. If the host container has a custom hostname (e.g. set via --hostname custom-scanner), then VMClarity will not be able to fetch the host container from its hostname and the plugin support will not work.
[x] Bug Fix  
[ ] New Feature …
=> fix: use custom network for plugin communication

plugins/sdk-python/example/Dockerfile.test
Updating the Python version in the test Dockerfile of the example of the python plugin SDK, because v3.9 is not available anymore in the repositories of Ubuntu 24.04 that was updated here: 
https://github.com/openclarity/vmclarity/commit/cb413065f1236cee15773a6d185748dbe17eda25
This causes building the docker image to fail:
```
22.85 E: Unable to locate package python3.9
22.85 E: Couldn't find any package by glob 'python3.9'
22.85 E: Couldn't find any package by regex 'python3.9'
------
Dockerfile.test:23
--------------------
22 |     
23 | >>> RUN apt-get update &&  \
24 | >>>     apt-get install --no-install-recommends -y python3.9 python3-venv && \
25 | >>>        apt-get clean && rm -rf /var/lib/apt/lists/*
26 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c …
```
=> chore(deps): update Python version to 3.12

scanner/families/manager_test.go
New test case for verification of the family manager timeout handling.
[ ] Bug Fix  
[ ] Refactor  
=> test: add family manager timeout test

.families.yaml, orchestrator/watcher/assetscan/families.go, scanner/config/local_grype.go, scanner/scanner/grype/local_grype.go
There is a known issue with grype, it occasionally get stuck when a new database version is published:
https://github.com/anchore/grype/issues/1731
To solve this problem, timeouts of the HTTP client have been made configurable: 
https://github.com/anchore/grype/commit/7c849c33b01396cb2346e656f01376d8474f3d7a
This PR allows VMClarity users to configure these timeouts. 
[ ] Bug Fix  
[ ] Refactor  
=> feat: make grype timeouts configurable

.families.yaml, scanner/families/malware/clam/clam.go, scanner/families/malware/clam/config/config.go
Adding the capability to exclude directories and files from ClamAV.
https://linux.die.net/man/1/clamscan
```
--exclude=REGEX, --exclude-dir=REGEX
Don't scan file/directory names matching regular expression. These options can be used multiple times.
```
[ ] Bug Fix  
[ ] Refactor  
=> feat: add the capability to exclude directories and files from ClamAV

testenv/aws/aws.go, testenv/aws/utils.go, testenv/azure/azure.go, testenv/azure/utils.go, testenv/gcp/gcp.go, testenv/utils/ssh.go
Some small improvements I made during testing. Tested with Azure and AWS.
[X] Bug Fix  
[ ] Refactor  
=> test: e2e test improvements

.golangci.yml
Remove deprecated linters from disabled list to avoid warning messages
[ ] Bug Fix  
[ ] Refactor  
=> ci: remove deprecated linters

.github/workflows/post-release.yaml
As per the [documentation](https://docs.github.com/en/rest/git/refs?apiVersion=2022-11-28#create-a-reference), `contents: write` permission is needed for creating references.
[X] Bug Fix  
[ ] Refactor  
=> ci: fix post-release workflow permissions

.github/workflows/manual-build-and-push.yaml
Add new workflow to build container images manually from a specific branch.
[ ] Bug Fix  
[ ] Refactor  
=> ci: add new workflow to build container images manually

scanner/families/malware/clam/clam.go
=> fix: add quotes to clamscan exclude options

cli/cli.go, cli/cli_test.go, utils/fsutils/blockdevice/darwin.go, utils/fsutils/diskutil/blockdevice.go, utils/fsutils/diskutil/diskutil.go, utils/fsutils/diskutil/parse.go, utils/fsutils/diskutil/parse_test.go, utils/fsutils/diskutil/testdata/diskutil.txt
First part of https://github.com/openclarity/vmclarity/issues/356, add support to mount and unmount NTFS devices. No further changes are required in the mount/unmount logic and the mount option remain the same.
**Steps to test NTFS Support**
1.	Launch ubuntu instance on AWS
2.	Create EBS volume and attach it to the instance (device name /dev/xvdbn)
3.	Check that the new attached volume is listed as a block device (`lsblk`)
4.	Convert to ntfs (`sudo mkfs.ntfs -f /dev/xvdbn`)
5.	Run the following script to mount and unmount the NTFS block device
```go
// utils/fsutils/cmd/main.go
package main
import (
"context"
"fmt"
"os"
"strings"
"github.com/google/uuid"
"github.com/openclarity/vmclarity/utils/fsutils/blockdevice"
"github.com/openclarity/vmclarity/utils/fsutils/filesystem" …
```
=> feat(cli): support ntfs mount and unmount

Makefile, RELEASE.md
- added automatic stashing in`multimod-prerelease` make target instead of warning in the docs
- added additional info and post release steps to the release docs
=> docs(ci): improve docs on release flow

scanner/families/plugins/runner/runner.go
If an error occurs, we send the result back to the family manager on a channel and return from the function:
```
if err := rr.WaitReady(ctx); err != nil {
s.sendResults(retResults, fmt.Errorf("failed to wait for plugin scanner to be ready: %w", err))
return
}
```
As part of the return, the deferred `Stop` and `Remove` lifecycle functions begin to run:
```
defer func() {
if err := rr.Stop(ctx); err != nil {
s.logger.WithError(err).Errorf("failed to stop runner")
}
// TODO: add short wait before removing to respect container shutdown procedure
if err := rr.Remove(ctx); err != nil {
s.logger.WithError(err).Errorf("failed to remove runner")
}
}() //nolint:errcheck
```
Once the family manager gets the result in the result channel, it does not really care if the underlying goroutines are …
=> fix(plugin): fix plugin family runner race condition

scanner/utils/containerrootfs/example/main.go, scanner/utils/containerrootfs/todirectory.go, scanner/utils/containerrootfs/totempdirectory.go
So if the image metadata is also needed, we don't get the image twice.
Put getting the image in a separate function so that if the image metadata is also needed outside of extracting it to a directory, we don't need to get the image twice.
=> refactor(scanner): separate GetImage from ToDirectory

.github/workflows/reusable-verification.yml, ui/.eslintrc, ui/package-lock.json, ui/package.json, ui/src/components/DoublePaneDisplay/index.test.tsx, ui/src/components/Form/form-fields/CronField/index.jsx, ui/vite.config.ts
This PR adds eslint, prettifier and react testing library to the frontend codebase.
=> ci(ci): add eslint

ui/src/components/Table/index.jsx, ui/src/layout/AssetScans/AssetScansTable.jsx, ui/src/layout/Assets/AssetsForFindingTable.jsx, ui/src/layout/Assets/AssetsTable.jsx, ui/src/layout/Findings/AssetCountDisplay.jsx, ui/src/layout/Findings/Exploits/ExploitDetails.jsx, ui/src/layout/Findings/Exploits/TabExploitDetails.jsx, ui/src/layout/Findings/Malware/MalwareDetails.jsx, ui/src/layout/Findings/Malware/TabMalwareDetails.jsx, ui/src/layout/Findings/Misconfigurations/MisconfigurationDetails.jsx, ui/src/layout/Findings/Misconfigurations/TabMisconfigurationDetails.jsx, ui/src/layout/Findings/Packages/PackageDetails.jsx, ui/src/layout/Findings/Packages/TabPackageDetails.jsx, ui/src/layout/Findings/Rootkits/RootkitDetails.jsx, ui/src/layout/Findings/Rootkits/TabRootkitDetails.jsx, ui/src/layout/Findings/Secrets/SecretDetails.jsx, ui/src/layout/Findings/Secrets/TabSecretDetails.jsx, ui/src/layout/Findings/Vulnerabilities/TabVulnerabilityDetails.jsx, ui/src/layout/Findings/Vulnerabilities/VulnerabilityDetails.jsx, ui/src/layout/Findings/utils.jsx, ui/src/layout/Scans/Scans/ScansTable.jsx, ui/src/utils/systemConsts.js, ui/src/utils/utils.jsx
There was a change recently in #1758 in which the `asset` field was removed from the `finding` object, and a new `assetFinding` structure was introduced in the API spec to make the relationship between assets and findings **n:n**, so the _Asset details_ tab (displaying details of one Asset the finding was found in) from the Finding details page was removed.
Put back an _Assets_ tab, but list all assets that the particular finding is related to.
- The `First seen` and `Last seen` sections were put next to each other to gain some vertical space
- An `Asset count` section was added to the bottom of the _General details_ part, displaying the number of currently active assets, followed by the total number of assets in parentheses
- At the top, a new `Assets` tab was added
Default state of the …
=> feat(ui): add related Assets tab to Finding detail pages

scanner/config.go
- Adding inputs for exploits was missing, added it.
=> fix(scanner): add missing append for exploits

api/server/database/gorm/odata.go, orchestrator/processor/assetscan/common.go
Due to some changes since v0.7.1 saving specific kinds of finding data to the DB started to fail, so they were not displayed on the UI either. One problem was missing odatasql meta fields from the Secret finding type, the other is a function not returning the finding ID after unsuccessful update, so the next method in the chain could patch it.
Fixes #1897
=> fix(api): return missing finding data

api/types/providerstatus.go, e2e/provider_test.go
This PR creates a function to set the `Status` of a `Provider` object.
=> refactor(api): provider status

renovate.json
Quick fix for the Renovatebot config to use the correct name for the manager to update Python dependencies.
=> fix(ci): use correct Renovatebot manager for Python

plugins/runner/go.mod, plugins/runner/internal/runtimehandler/binary/handler.go, plugins/runner/internal/runtimehandler/docker/handler.go, plugins/runner/internal/runtimehandler/types.go, plugins/runner/runner.go
=> fix(plugin): make output file path configurable by pluginruntimehandler

plugins/runner/internal/runtimehandler/binary/handler.go, plugins/runner/internal/runtimehandler/docker/handler.go, scanner/families/plugins/runner/runner.go
=> refactor(plugin): add package level mutexes to plugin runtimehandlers

Makefile
Added renovate fix targets for generating API and format UI code automatically just in case, also a high-level `renovate-fix` target that runs all the individual renovate fix targets to make dealing with renovatebot PRs easier. The only caveat is that it is recommended to be run with the "-i" flag like `make -i renovate-fix` so it won't return with a git error at the first step in which there is nothing to be committed.
=> feat(ci): extend renovate-fix make targets

ui/src/layout/AssetScans/AssetScansTable.jsx, ui/src/layout/AssetScans/TabAssetScanDetails.jsx, ui/src/layout/Assets/AssetsForFindingTable.jsx, ui/src/layout/Assets/AssetsTable.jsx, ui/src/layout/Scans/ConfigurationReadOnlyDisplay.jsx
Fixing some fields on the UI which didn't display any data despite available just needed a transformation or access to another field.
Fixes openclarity/openclarity#666
| Before | After |
|     :---:      |     :---:      |
| ![Screenshot 2024-08-08 at 17 59 29](https://github.com/user-attachments/assets/2ef3459e-3146-4458-affd-0beee5df5a21) | ![Screenshot 2024-08-08 at 18 00 23](https://github.com/user-attachments/assets/8a825907-26bc-4dae-959f-17e27f96a518) |
| ![Screenshot 2024-08-08 at 17 59 40](https://github.com/user-attachments/assets/c21d34e8-041c-46d0-a424-98885359830a) | ![Screenshot 2024-08-08 at 18 00 57](https://github.com/user-attachments/assets/9f2ed663-d257-44b3-a358-c7e8e87298d0) |
| ![Screenshot 2024-08-08 at 17 59 …
=> fix(ui): data display

ui/src/layout/AssetScans/AssetScanDetails.jsx, ui/src/layout/Dashboard/CounterDisplay/index.jsx, ui/src/layout/Dashboard/index.jsx, ui/src/layout/Findings/Exploits/ExploitsTable.jsx, ui/src/layout/Findings/FindingsDetailsPage.jsx, ui/src/layout/Findings/FindingsTablePage.jsx, ui/src/layout/Findings/Malware/MalwareTable.jsx, ui/src/layout/Findings/Misconfigurations/MisconfigurationTable.jsx, ui/src/layout/Findings/Packages/PackagesTable.jsx, ui/src/layout/Findings/Rootkits/RootkitsTable.jsx, ui/src/layout/Findings/Secrets/SecretsTable.jsx, ui/src/layout/Findings/Vulnerabilities/VulnerabilitiesTable.jsx, ui/src/layout/Scans/Configurations/ConfigurationDetails/TabConfiguration.jsx, ui/src/layout/Scans/Scans/ScansTable.jsx, ui/src/layout/Scans/index.jsx, ui/src/layout/detail-displays/AssetDetails/AssetScansDisplay.jsx
Narrow down the returned data from queries only to the necessary fields using the `select` OData option to reduce load time.
Fixes openclarity/openclarity#720
=> perf(ui): improve UI queries to reduce load time

ui/src/layout/AssetScans/AssetScanDetails.jsx, ui/src/layout/Assets/AssetDetails.jsx, ui/src/layout/Findings/Exploits/ExploitDetails.jsx, ui/src/layout/Findings/Malware/MalwareDetails.jsx, ui/src/layout/Findings/Misconfigurations/MisconfigurationDetails.jsx, ui/src/layout/Findings/Packages/PackageDetails.jsx, ui/src/layout/Findings/Rootkits/RootkitDetails.jsx, ui/src/layout/Findings/Secrets/SecretDetails.jsx, ui/src/layout/Findings/Vulnerabilities/VulnerabilityDetails.jsx, ui/src/layout/Scans/Configurations/ConfigurationActionsDisplay/index.jsx, ui/src/layout/Scans/Scans/ScanDetails.jsx, ui/src/utils/utils.jsx
=> chore(ui): small cleanup
