openclarity/vmclarity

.github/stale.yml
The current messaging doesn't provide information about how to un-stale an issue or the time scales for when the issue will move into stale/closed. This commit updates the messaging to make it more approachable.
[ ] Bug Fix  
[ ] Refactor  
[X] Documentation  
=> Update stalebot message to explain how to keep an issue alive

ui/src/layout/detail-displays/ScanDetails/index.js, ui/src/utils/utils.js
Set assets scans number in the button to be the total number instead of completed. 
Show scan duration even if it's not ended yet.
[ ] Bug Fix  
[X] Refactor  
=> Scan drill down modifications - asset scans num & duration

ui/src/components/DetailsPageWrapper/index.js, ui/src/components/ScanProgressBar/index.js, ui/src/hooks/useFetch.js, ui/src/layout/Scans/Scans/ScanActionsDisplay/index.js, ui/src/layout/Scans/Scans/ScanDetails.js, ui/src/layout/Scans/Scans/ScansTable.js, ui/src/layout/Scans/Scans/index.js
Added a stop scan button to the scan table and details
[ ] Bug Fix  
[x] Refactor  
=> UI - stop scan

ui/src/layout/AssetScans/StatusIndicator/index.js
UI - adding the aborted status to assets scans
[ ] Bug Fix  
[ ] Refactor  
=> UI - add aborted state to asset scans

cli/pkg/presenter/vmclarity.go
=> fix misconfiguration export logic

ui/src/components/Tag/index.js, ui/src/layout/AssetScans/AssetScansTable.js, ui/src/layout/Assets/AssetsTable.js, ui/src/layout/Findings/FindingsTablePage.js, ui/src/layout/Scans/ConfigurationReadOnlyDisplay.js, ui/src/layout/Scans/Configurations/ConfigurationsTable/index.js, ui/src/layout/Scans/ScanConfigWizardModal/index.js, ui/src/layout/Scans/utils.js, ui/src/layout/detail-displays/AssetDetails/index.js, ui/src/utils/utils.js
UI - added more information to the asset table and details pages
[ ] Bug Fix  
[ ] Refactor  
=> UI - expanded asset details

ui/package-lock.json, ui/package.json, ui/src/components/CopyButton/index.js, ui/src/components/Filter/index.js, ui/src/components/TablePage/index.js, ui/src/context/FiltersProvider.js, ui/src/layout/Assets/AssetsTable.js, ui/src/layout/Scans/Scans/ScanDetails.js
Updated UI filters to be represented in the URL
[ ] Bug Fix  
[ ] Refactor  
=> UI filters in URL

ARCHITECTURE.md, GOALS.md, README.md, TOUR.md, installation/aws/README.md
Add a demo gif, quick start and roadmap to README
=> docs: Add a demo gif, quick start and roadmap to README

Dockerfile.cli, Makefile
- added a digest to the vmclarity-cli base image
- fix makefile to not fail on local multiarch build
[x] Bug Fix  
[ ] Refactor  
=> fix: dont build multiarch locally

runtime_scan/pkg/orchestrator/scanconfigwatcher/schedule.go, runtime_scan/pkg/orchestrator/scanconfigwatcher/watcher.go, runtime_scan/pkg/orchestrator/scanresultwatcher/watcher.go, runtime_scan/pkg/orchestrator/scanwatcher/watcher.go
Remove UTC() unnecessary conversion.
[ ] Bug Fix  
[x] Refactor  
=> refactor: rm UTC() unnecessary conversion

.golangci.yml, go.mod, go.sum
Bump version for `github.com/anchore/sqlite` which includes the patch for supporting `gorm.io` `v1.25.0.`
Fixes: #382 
[ ] Bug Fix  
[ ] Refactor  
=> feat: bump github.com/anchore/sqlite

ui/src/components/DetailsPageWrapper/index.js, ui/src/layout/AssetScans/AssetScanDetails.js, ui/src/layout/AssetScans/AssetScansTable.js, ui/src/layout/AssetScans/TabAssetScanDetails.js, ui/src/layout/Assets/AssetDetails.js, ui/src/layout/Assets/AssetsTable.js, ui/src/layout/Findings/Exploits/ExploitDetails.js, ui/src/layout/Findings/FindingsDetailsPage.js, ui/src/layout/Findings/Malware/MalwareDetails.js, ui/src/layout/Findings/Misconfigurations/MisconfigurationDetails.js, ui/src/layout/Findings/Packages/PackageDetails.js, ui/src/layout/Findings/Rootkits/RootkitDetails.js, ui/src/layout/Findings/Secrets/SecretDetails.js, ui/src/layout/Findings/Vulnerabilities/VulnerabilityDetails.js, ui/src/layout/Scans/Configurations/ConfigurationDetails/index.js, ui/src/layout/Scans/Configurations/ConfigurationsTable/index.js, ui/src/layout/Scans/Scans/ScanDetails.js
- Updated the API calls used by the UI with the relevant expand and select keys
- Added the SBOM scan status to the asset scan details
[ ] Bug Fix  
[x] Refactor  
=> APIs select/expand updates and asset scans sbom status

runtime_scan/pkg/provider/aws/volume.go
Fixes #448 by searching for `attached` volume attachment state instead of accessing. 
Simplifies the code a bit similarly to `IsReady` 
[x] Bug Fix  
[ ] Refactor  
=> fix: resolve aws volume attachment check

runtime_scan/pkg/orchestrator/common/queue.go
If we are working with q.queue we must hold the lock to make sure there is no race conditions. During Dequeue we weren't holding the lock when we checked the length of queue.
After this commit we hold the lock to check the length of q.queue. If the queue is empty we unlock the mutex to allow an item to be added to the queue while we wait for a itemAdded notification. The lock is then regained to dequeue the item that was added.
If the queue isn't empty we continue to hold the lock and move straight to dequeue the item defering the unlock until the function completes.
[X] Bug Fix  
[ ] Refactor  
=> fix: Fix data race checking the queue length in dequeue

backend/pkg/database/demo.go, ui/src/components/Form/form-fields/CheckboxField/index.js, ui/src/components/ToggleButton/index.js, ui/src/layout/Assets/AssetsTable.js
*Added the "hide terminated" filter to the assets page
*Fixed onChange issue in the ToggleButton and CheckboxField components
[x] Bug Fix  
[ ] Refactor  
=> UI terminated filter

docs/scanConfig.json, docs/test_e2e.md, docs/testplans/abort-scan.md
https://github.com/openclarity/vmclarity/issues/457
Adjust `scanConfig` examples by updating the scope object to reflect the changes introduced by https://github.com/openclarity/vmclarity/pull/438 
Tested in AWS with empty scope, with tag scope and with region+vpc+secgroup scope.
[ ] Bug Fix  
[ ] Refactor  
=> docs: Update scope in scan configuration examples

installation/aws/VmClarity.cfn
Bump the exploit db server to a newer version, because the current one crashloops because of the inTheWild db fetching.
[x] Bug Fix  
[ ] Refactor  
=> fix(cfn): update explot db server version

installation/azure/vmclarity-UI.json, installation/azure/vmclarity.bicep, installation/azure/vmclarity.json, installation/azure/vmclarityDeployModule.bicep, installation/gcp/dm/components/vmclarity-server.py.schema, installation/gcp/dm/vmclarity.py.schema
Update exploit db image tag in Azure and GCP.
[x] Bug Fix  
[ ] Refactor  
=> chore(exploitdb): update exploit db image tag in azure and gcp

.github/PULL_REQUEST_TEMPLATE.md
This PR fixes a wrong link to the contributing guide.
[ ] Bug Fix  
[ ] Refactor  
=> fix(link): contributing guide link

README.md
https://github.com/openclarity/vmclarity/issues/510
[ ] Bug Fix  
[ ] Refactor  
=> docs: add slack invite to README

README.md
Add GitHub workflow status and go report card badges to README file.
[ ] Bug Fix  
[ ] Refactor  
=> docs: add workflow status and go report card to readme file

e2e/README.md, e2e/abort_scan_test.go, e2e/basic_scan_test.go, e2e/default_scan_test.go, e2e/fail_scan_test.go, e2e/helpers.go, e2e/report.go, e2e/testenv/testenv.go
When a test fails, report relevant API data and docker service logs for debugging purposes.
[ ] Bug Fix  
[ ] Refactor  
=> feat(test): report api output and service logs on failure

.github/actionlint-matcher.json, .github/workflows/build-and-push-component.yaml, .github/workflows/ci.yml, .github/workflows/release.yaml, .github/workflows/reusable-build-and-push.yml, Makefile
Add `actionlint` to make testing of the CI workflows as part of the CI pipeline in order to catch possible issues with GH Actions early on.
[ ] Bug Fix  
[x] Refactor  
=> feat(ci): add actionlint

README.md
Currently the Azure install button is broken, since it points to a non existing branch.
This PR changes the link to point to main.
[ *] Bug Fix  
[ ] Refactor  
[* ] Documentation  
=> Doc (README): Fix Azure install link

.github/workflows/build-and-push-component.yaml, .github/workflows/ci.yml, .github/workflows/main-merge.yml, .github/workflows/release.yaml, .github/workflows/reusable-build-and-push.yml
* fix merging multi-arch container images
* push development container images to dedicated package repositories
* post comment on pull requests with corresponding container images.
[x] Bug Fix  
[x] Refactor  
=> feat(ci): push dev images to dedicated repo

.github/workflows/ci.yml, .github/workflows/main-merge.yml, .github/workflows/release.yaml, .github/workflows/reusable-verification.yml, Makefile
* split verification into multiple jobs running parallel
* add caching for `licensei`
* add caching for `golangci-lint`
* add caching of Go dependencies and builds
[ ] Bug Fix  
[x] Refactor  
=> refactor(ci): verification workflow

.github/workflows/cache-cleanup.yml
Delete caches for Pull Requests on merge/close in order to avoid valid cache eviction due to limited storage.
[ ] Bug Fix  
[ ] Refactor  
=> feat(ci): cleanup cache for PRs

pkg/orchestrator/provider/azure/client.go, pkg/orchestrator/provider/azure/config.go, pkg/orchestrator/provider/gcp/client.go, pkg/orchestrator/provider/gcp/config.go, pkg/shared/backendclient/client.go
Small refactor to:
* Fix spelling
* Improve consistency by using config as pointer in all providers
[ ] Bug Fix  
[x] Refactor  
=> refactor: fix spelling and improve consistency

.github/scripts/cache-cleanup.sh, .github/workflows/cache-cleanup.yml
Fix cache cleanup script triggered in CI for PR close and scheduled events.
[x] Bug Fix  
[ ] Refactor  
=> fix(ci): cache cleanup script

Dockerfile.apiserver, Dockerfile.cli, Dockerfile.orchestrator, Dockerfile.ui, Dockerfile.uibackend, pkg/orchestrator/provider/docker/client.go
* use separate step to download and cache dependencies
* use bind mount instead of COPY in order to avoid unnecessary copying of source code
[ ] Bug Fix  
[x] Refactor  
=> refactor: Dockerfiles

.github/workflows/reusable-verification.yml, .licensei.toml
Re-enable license check in CI.
[x] Bug Fix  
[ ] Refactor  
=> fix(ci): re-enable license check

.github/workflows/ci.yml, .github/workflows/reusable-verification.yml, Makefile, makefile.d/10-helpers.mk, makefile.d/20-tools.mk
* moving helpers and installing tools to separate Makefiles
* use built-in `info` for printing messages
* add sections to group make target(s)
* use make variables instead of environment variables in make target(s)
* add missing targets to help
[ ] Bug Fix  
[x] Refactor  
=> refactor: Makefile

.github/workflows/ci.yml
Let's gate PRs with e2e tests 🥳 
[ ] Bug Fix  
[ ] Refactor  
=> feat(ci): make e2e tests gating

README.md
Fixes #885 
[ ] Bug Fix  
[ ] Refactor  
[X] Documentation  
=> docs(readme): updated roadmap link

.github/workflows/semantic-pr.yml
Ensure that Pull Request title is aligned with [Conventional Commit Spec](https://www.conventionalcommits.org/en/v1.0.0/).
This allows us to generate well-formatted changelog in release notes.
[ ] Bug Fix  
[ ] Refactor  
=> feat(ci): lint PR title

installation/kubernetes/helm/vmclarity/README.md, installation/kubernetes/helm/vmclarity/templates/orchestrator/deployment.yaml, installation/kubernetes/helm/vmclarity/values.yaml
* always set `VMCLARITY_ORCHESTRATOR_PROVIDER`
* add `docker` provider config to Values for testing purposes
[ ] Bug Fix  
[x] Refactor  
=> refactor(helm): provider in Orchestrator config

.github/workflows/semantic-pr.yml
* extend the list of types to include all the commonly used types
* group scopes based on domains separated empty lines. Empty lines in scopes definition are ignored.
[ ] Bug Fix  
[ ] Refactor  
=> ci: update PR linter config

Makefile
Run `git-cliff` with different options in CI and locally in order to generate the correct list of changes.
[ ] Bug Fix  
[ ] Refactor  
=> ci: fix release notes

.github/dependabot.yml
Configure `dependabot` to group update of certain dependencies (e.g. `aws-sdk`) into a single PR.
[ ] Bug Fix  
[ ] Refactor  
=> ci: group dependency updates

installation/aws/VmClarity.cfn, installation/azure/vmclarity-UI.json, installation/azure/vmclarity.bicep, installation/azure/vmclarity.json, installation/azure/vmclarityDeployModule.bicep, installation/docker/docker-compose.yml, installation/docker/image_override.env, installation/gcp/dm/components/vmclarity-server.py.schema, installation/gcp/dm/vmclarity.py.schema, installation/kubernetes/helm/vmclarity/README.md, installation/kubernetes/helm/vmclarity/values.yaml
Bump `freshclam-mirror` container image version to `v0.3.0`.
[ ] Bug Fix  
[ ] Refactor  
=> chore(deps): bump freshclam-mirror to v0.3.0

.github/dependabot.yml
Update `dependabot` configuration to group `containerd` related updates into a single PR.
[ ] Bug Fix  
[ ] Refactor  
=> ci: group containerd updates

.github/workflows/reusable-verification.yml
Test/verify the Azure/Bicep deployment package in CI.
[ ] Bug Fix  
[ ] Refactor  
=> ci: add linting for Azure/Bicep package

.github/dependabot.yml
Update `dependabot` config to group Kubernetes dependency updates.
[ ] Bug Fix  
[ ] Refactor  
=> ci: group k8s dep updates

.dockerignore, .gitignore
This PR adds `.envrc` to the `.gitignore` file and `go.work*` to the `.dockerignore` file.
[ ] Bug Fix  
[ ] Refactor  
=> chore: add .envrc to .gitignore, add go.work* to .dockerignore

.github/dependabot.yml
Group docker dependency updates.
[ ] Bug Fix  
[ ] Refactor  
=> ci: group docker dependency updates

testenv/docker/docker_test.go, testenv/kubernetes/helm/chart_test.go, testenv/kubernetes/helm/loader_test.go
Fix broken tests in `testenv` module.
[x] Bug Fix  
[ ] Refactor  
=> test(testenv): fix broken tests

.github/workflows/reusable-end-to-end-testing.yml, .licensei.toml, Makefile
Add the following improvements/fixes to `Makefile`:
* optimize build flags for binary builds
* fix target dependencies for binary build targets
* fix docker build/push targets as environment variables were set incorrectly
* refactor target for e2e in order to be able to use it in CI
* fix license check target
[ ] Bug Fix  
[ ] Refactor  
=> chore: improve makefile

renovate.json
* pin docker images by digest
* rm go mod massage post processor
[ ] Bug Fix  
[ ] Refactor  
=> ci: adjust renovate config

installation/docker/docker-compose.yml, installation/docker/gateway.conf
Fix nginx configuration for `gateway` service after changing container image to the `nginxinc/nginx-unprivileged` from `nginx`.
[x] Bug Fix  
[ ] Refactor  
=> fix: nginx config for gateway service

renovate.json
* add description to custom/package rules
* enable vulnerability alerts
* rebase dependency update PRs only on conflict
* ignore deprecated `v1` versions for `trivy-db`
* use `latest` tag for VMClarity container images
[ ] Bug Fix  
[ ] Refactor  
=> ci: improve renovatebot config

installation/azure/vmclarity-UI.json
Fix `yara-rule-server` container image version in Azure deployment manifest.
[x] Bug Fix  
[ ] Refactor  
=> fix: Yara Rule Server version in Azure deployment

utils/fsutils/lsblk/internal/scan.go, utils/fsutils/lsblk/lsblk.go
* allow filtering based on device path when listing available devices
* refactor `List` command
[ ] Bug Fix  
[x] Refactor  
=> refactor: add filtering to utils/lsblk

utils/fsutils/mount/unix.go
Add support for `umount` to `fsutils/mount` pkg.
[ ] Bug Fix  
[ ] Refactor  
=> feat: add support for umount to fsutils/mount

api/client/go.mod, api/server/go.mod, api/types/go.mod, api/types/go.sum, cli/go.mod, containerruntimediscovery/client/go.mod, containerruntimediscovery/client/go.sum, containerruntimediscovery/server/go.mod, containerruntimediscovery/types/go.mod, containerruntimediscovery/types/go.sum, e2e/go.mod, e2e/testdata/go.mod, installation/go.mod, orchestrator/go.mod, plugins/runner/go.mod, plugins/sdk/go/example/go.mod, plugins/store/kics/go.mod, provider/go.mod, scanner/go.mod, testenv/go.mod, uibackend/client/go.mod, uibackend/server/go.mod, versions.yaml
=> release: prepare version v0.7.0-rc.1

plugins/sdk/python/README.md, plugins/sdk/python/example/Dockerfile, plugins/sdk/python/example/Dockerfile.test, plugins/sdk/python/example/requirements.txt
- Added a new Dockerfile, that uses the `requirements.txt` file instead of building from local files
[ ] Bug Fix  
[ ] Refactor  
=> refactor: update python sdk

installation/kubernetes/helm/vmclarity/templates/orchestrator/deployment.yaml
Fix grype server address in helm template.
[X] Bug Fix  
[ ] Refactor  
=> fix: grype server address in helm template

api/types/plugin_adapter.go, installation/docker/docker-compose.yml
- @lgecse came up with this temp solution for the ui-backend fail: #1657
[X] Bug Fix  
[ ] Refactor  
=> fix: temp solution for ui-backend failing

installation/kubernetes/helm/vmclarity/templates/NOTES.txt
Some useful info that is going to be printed after a successful Helm install, just like in [Kubeclarity](https://github.com/openclarity/kubeclarity/blob/main/charts/kubeclarity/templates/NOTES.txt)!
[ ] Bug Fix  
[ ] Refactor  
[X] Documentation  
=> feat: helm install notes for kubernetes provider

renovate.json
Ignore plugin modules to avoid the creation of PRs like https://github.com/openclarity/vmclarity/pull/1701
[ ] Bug Fix  
[x] Refactor  
=> chore: add missing mods to renovate ignore

api/client/go.mod, api/server/go.mod, api/types/go.mod, cli/go.mod, containerruntimediscovery/client/go.mod, containerruntimediscovery/server/go.mod, containerruntimediscovery/types/go.mod, e2e/go.mod, installation/go.mod, orchestrator/go.mod, plugins/runner/go.mod, plugins/sdk-go/example/go.mod, plugins/store/kics/go.mod, provider/go.mod, scanner/go.mod, testenv/go.mod, uibackend/client/go.mod, uibackend/server/go.mod, versions.yaml
Release pull request
[ ] Bug Fix  
[ ] Refactor  
=> release: prepare version v0.7.0

.github/workflows/semantic-pr.yml
=> chore: add new PR scopes

api/client/go.mod, api/server/go.mod, api/types/go.mod, cli/go.mod, containerruntimediscovery/client/go.mod, containerruntimediscovery/server/go.mod, containerruntimediscovery/types/go.mod, e2e/go.mod, installation/go.mod, orchestrator/go.mod, plugins/runner/go.mod, plugins/sdk-go/example/go.mod, plugins/store/kics/go.mod, provider/go.mod, scanner/go.mod, testenv/go.mod, uibackend/client/go.mod, uibackend/server/go.mod, versions.yaml
Release v0.7.1
[ ] Bug Fix  
[ ] Refactor  
=> release: v0.7.1

ui/src/layout/Dashboard/FindingsTabsWidget/index.jsx, ui/src/layout/Findings/utils.jsx, ui/src/layout/detail-displays/Findings/index.jsx
Some quick fixes related to the asset-findings relationship changes, I recommend looking at the commits and their descriptions for more information!
[X] Bug Fix  
[ ] Refactor  
=> fix: asset-findings UI fixes

.github/workflows/semantic-pr.yml
=> ci: require scope for pull requests

.github/PULL_REQUEST_TEMPLATE.md, cliff.toml
- format checkboxes, hide instructions in pull request template
- add emojis and a Highlight section to the release template by default so it is more pleasing to the eye
- [inspiration](https://gist.github.com/parmentf/035de27d6ed1dce0b36a)
- did not implement hiding dependency updates under a dropdown, because they are omitted by default (`{ message = "^chore\\(deps\\):", skip = true },` in the commit parser)
=> style(ci): improve PR and release templates

Makefile, RELEASE.md, api/client/go.mod, api/server/go.mod, api/types/go.mod, cli/go.mod, containerruntimediscovery/client/go.mod, containerruntimediscovery/server/go.mod, containerruntimediscovery/types/go.mod, e2e/go.mod, installation/go.mod, orchestrator/go.mod, plugins/runner/go.mod, plugins/sdk-go/example/go.mod, plugins/store/kics/go.mod, provider/go.mod, scanner/go.mod, testenv/go.mod, uibackend/client/go.mod, uibackend/server/go.mod, utils/go.mod, versions.yaml
Release v0.7.2 and small prerelease command fix
=> release(ci): prepare version v0.7.2

.github/workflows/semantic-pr.yml
=> feat(ci): add general scope

.github/workflows/reusable-end-to-end-testing.yml
- Changes Kind install action from https://github.com/engineerd/setup-kind to https://github.com/helm/kind-action
=> chore(ci): change helm install action

scanner/families/plugins/runner/runner.go
A new plugin runner instance is created for each input, that means that none of the synchronization mechanisms work in the underlying code (each has it's own mutex).
https://github.com/openclarity/vmclarity/blob/bcdab9c5380728b7a27308d2b096972c2f632b94/scanner/families/plugins/runner/runner.go#L61
This leads to race conditons in several places (docker network creation, image pulling, etc).
```
WARNING[2024-07-15T19:23:10Z] Scan job "kics" for input rootfs:/terragoat3/ failed  input="rootfs:/terragoat3/" app=vmclarity family=plugins error="error during plugin execution: failed to start plugin runner: failed to create plugin container: failed to start container: Error response from daemon: network vmclarity-plugins-network is ambiguous (5 matches found on name)" scanner=kics …
```
=> fix(plugin): fix plugin runner race condition

cli/state/testdata/effective-config.json, scanner/families/exploits/exploitdb/config/config.go, scanner/families/exploits/types/config.go, scanner/families/infofinder/types/config.go, scanner/families/malware/clam/config/config.go, scanner/families/malware/types/config.go, scanner/families/malware/yara/config/config.go, scanner/families/misconfiguration/cisdocker/config/config.go, scanner/families/misconfiguration/lynis/config/config.go, scanner/families/misconfiguration/types/config.go, scanner/families/plugins/runner/config/config.go, scanner/families/plugins/types/config.go, scanner/families/rootkits/chkrootkit/config/config.go, scanner/families/rootkits/types/config.go, scanner/families/sbom/syft/config/config.go, scanner/families/sbom/trivy/config/config.go, scanner/families/sbom/types/config.go, scanner/families/secrets/gitleaks/config/config.go, scanner/families/secrets/types/config.go, scanner/families/vulnerabilities/grype/config/config.go, scanner/families/vulnerabilities/grype/config/local_grype.go, scanner/families/vulnerabilities/grype/config/remote_grype.go, scanner/families/vulnerabilities/trivy/config/config.go, scanner/families/vulnerabilities/types/config.go
Extend all scanner configuration fields with `json` tag.
=> feat(scanner): extend scanner configs with json tag

renovate.json
Refactor Renovatebot config according to the team's agreement on the attached issue.
Didn't test the changes but I can fine-tune it next week if something not working properly.
Fixes #1930
=> refactor(ci): fine-tune Renovatebot

README.md
=> docs(general): add capabilities and compatibility information

.github/PULL_REQUEST_TEMPLATE.md
Just a small addition to the PR template so it is easier to include a before/after table in the PR description.
=> docs(ci): extend PR template with before/after table
